### PR TITLE
`Date` ctr spec compliance

### LINKED ISSUE #5442: Date constructor with negative value argument
OS: Ubuntu 16.04 x86
chakra: 1.11.0.0-beta

Hi everyone,

I found an inconsistence on Date() with a negative value.
I was looking on ES6 specification about this issue but I didn't found an answer, maybe the correct way is convert the -0 to +0
as V8 and SpiderMonkey do.

Steps to reproduce:
```
d = new Date(-0);
print(Object.is(d.getTime(), +0))
```

Actual results:
false

Expected results:
true

V8 and SpiderMonkey works as expected.

### PR DESCRIPTION
**Pull request by ShortDevelopment**
According to the [spec](https://tc39.es/ecma262/#sec-date-value), the `Date` ctr should use the [`TimeClip` function](https://tc39.es/ecma262/#sec-timeclip).
Since it did not, `-0` was not converted to `+0` in the ctr (See issue #5442).

The ctr now uses `JavascriptDate::TimeClip` (moved from `IntlEngineInterfaceExtensionObject.cpp`).
However, this does not fix the original issue, as the underlying `JavascriptConversion::ToInteger` function is also [not spec compliant](https://tc39.es/ecma262/#sec-tointegerorinfinity) regarding the conversion from `-0` to `+0`.

This [non-compliance](https://tc39.es/ecma262/#sec-toint32) is also true for the other `ToIntXX` and `ToUintXX` functions (Not covered by this PR).

`JavascriptDate::TimeClip` should perhaps be placed somewhere else...

@rhuanjl (Could you please tag this PR with `hacktoberfest-accepted`?)

Fix #5442
Related to https://github.com/chakra-core/ChakraCore/pull/6743

### CODE REVIEW

File: lib/Runtime/Language/JavascriptConversion.cpp [hunk 1]
```diff
@@ -949,7 +950,7 @@ using namespace Js;
 
     double JavascriptConversion::ToInteger(double val)
     {
-        if(JavascriptNumber::IsNan(val))
+        if(JavascriptNumber::IsNan(val) || val == -0 || val == 0)
```
Comment (rhuanjl) [inline lib/Runtime/Language/JavascriptConversion.cpp]: Please can you use `JavascriptNumber::IsZero(val)` instead of `val == -0 || val == 0` that should work for this check (and is used for it elsewhere)

Also then please remove `JavascriptNumber::IsZero(val)` from the condition on lines 955 and 956.

File: lib/Runtime/Library/JavascriptDate.cpp [hunk 2]
```diff
@@ -215,6 +218,39 @@ namespace Js
         return pDate;
     }
 
+    // Implementation of ECMA 262 #sec-timeclip
+    // REVIEW(jahorto): Where is a better place for this function? JavascriptDate? DateUtilities? JavascriptConversion?
```
Comment (rhuanjl) [inline lib/Runtime/Library/JavascriptDate.cpp]: Please delete the `REVIEW(jahorto)` comment - we'll leave it here.

**Review by rhuanjl — COMMENTED** [review]
Thanks for this, just a couple of comments below

File: lib/Runtime/Library/JavascriptDate.cpp (hunk 2 above)
Comment (ShortDevelopment) [reply lib/Runtime/Library/JavascriptDate.cpp]: Sure, it’s a convenient place, regarding the use of `Math::Abs` 😀

**Review by rhuanjl — APPROVED** [review]
