### PR TITLE
Use Exception metadata to print error if Error.toString fails

### LINKED ISSUE #6567: An issue about redefining TypeError
###### Version

chakra-9e2f198

###### Test case

```js
TypeError.prototype.toString = function() {
    return Error;
};
var a = 1;
a();
```

###### Execution steps

    ./ChakraCore/out/Release/ch testcase.js

###### Output

```

```

###### Expected behavior

```
TypeError: a is not a function
```

###### Description

In the above test case, we redefine `TypeError`, but there is an exception in the redefined function (line 2). When executing the code, since `a` is not a function, `TypeError` will be thrown in line 5. Other engines seem to ignore the exception when redefining `TypeError` (line 2) when executing, and throw a `TypeError` exception normally, but chakra didn't . This seems to be incorrect.

### PR DESCRIPTION
**Pull request by rhuanjl**
This is a weird odd case and only a `ch` issue not a chakracore issue, BUT, the existing behaviour of silently exiting was clearly unhelpful.

1. Add JsGetExceptionWithMetadata to ch
2. Add handler in WScript::PrintException for Error.toString failure
3. Add test case

**Extra info:**
1. Runtime error objects have just 2 properties `.message` (error message only no other info) and `.stack - the `.stack` is a getter that triggers toString on the error object + adds urls and line numbers etc. unusable here because of the toString trigger inside it.
2. JsGetExceptionWithMetadata is an alternate API for getting an exception object + line, column, url etc.

Fix: #6567

### CODE REVIEW

File: bin/ch/ch.cpp [hunk 1]
```diff
@@ -520,6 +514,12 @@ HRESULT RunScript(const char* fileName, LPCSTR fileContents, size_t fileLength,
                 IfFailGo(messageQueue->ProcessAll(fileName));
             } while(!messageQueue->IsEmpty());
         }
+
+        // free the source for the serialized script case if it's not been handed to a managed object
+        if (!serializedCallbackInfo.freeingHandled && fileContentsFinalizeCallback != nullptr)
+        {
+            fileContentsFinalizeCallback((void*)fileContents);
```
Comment (rhuanjl) [inline bin/ch/ch.cpp:522]: Freeing serialised script source had to be moved down below the PrintException call - as GetExceptionWithMetaData accesses the source.

**Comment by rhuanjl** [comment]
@ppenzin this isn't that important but please could you take a look when you have a moment - it's fairly small at least - and I've tried to explain it all above.

File: bin/ch/ChakraRtInterface.cpp [hunk 2]
```diff
@@ -122,6 +123,7 @@ bool ChakraRTInterface::LoadChakraDll(ArgInfo* argInfo, HINSTANCE *outLibrary)
     m_jsApiHooks.pfJsrtGetArrayBufferStorage = (JsAPIHooks::JsrtGetArrayBufferStoragePtr)GetChakraCoreSymbol(library, "JsGetArrayBufferStorage");
     m_jsApiHooks.pfJsrtHasException = (JsAPIHooks::JsrtHasExceptionPtr)GetChakraCoreSymbol(library, "JsHasException");
     m_jsApiHooks.pfJsrtSetException = (JsAPIHooks::JsrtSetExceptionPtr)GetChakraCoreSymbol(library, "JsSetException");
+    m_jsApiHooks.pfJsrtGetAndClearExceptionWithMetadata = (JsAPIHooks::JsrtGetAndClearExceptiopnWithMetadataPtr)GetChakraCoreSymbol(library, "JsGetAndClearExceptionWithMetadata");
```
Comment (rhuanjl) [inline bin/ch/ChakraRtInterface.cpp:126]: I don't know why ch doesn't just link to CC and call CC APIs directly but for whatever reason it wraps them with the ChakraRTInterface class - this call gets the JsGetAndClearExceptionWithMetadata function from CC, related edits in ChakraRtInterface.h  provide the pointer it will be stored in.

EDIT: looked at it a bit more - this indirection is to support run time dynamic linking on windows; I'm not sure what benefit there is to that - if we update the build files to link directly we could delete out quite a bit of code.

Comment (ppenzin) [reply bin/ch/ChakraRtInterface.cpp:126]: Could this be another Chakra-full relic? @Penguinwizzard do you know anything about this?

**Review by ppenzin — APPROVED** [review]
