### PR TITLE
CI cleanup

### LINKED ISSUE #319: Fix timezone-sensitive tests (disabled in Jenkins)
There are a handful of tests which by their nature are timezone-sensitive (testing Date APIs). Because the execution of some Javascript Date APIs is dependent on the system time zone, the tests only work when run in the time zone in which the baselines were created (in our case, Pacific Time [UTC-8]).

The Jenkins machines are configured with UTC time and so we noticed that these tests would fail in any other timezone. To work around the problem for now, we disabled these tests in Jenkins.

It would be nice to add a way to enable these tests.

My thoughts:
- Some of these tests may not need to depend on the time zone. If possible, modify the tests to make them more general (as long as we keep exercising the same code paths).
- Add a flag to the test runner (`rl.exe`) and/or `ch.exe` which provides the ability to spoof the system timezone for tests, so that we can test the right code paths within ChakraCore which do depend on the system's reported time zone.

To locate the affected tests which were disabled in Jenkins, you can run:
`git grep -n -C 3 "timezone-sensitive"`

/cc @digitalinfinity @tcare @ianwjhalliday @kunalspathak FYI

Converted from [VSO 5239718](https://microsoft.visualstudio.com/web/wi.aspx?pcguid=cb55739e-4afe-46a3-970f-1b49d8ee7564&id=5239718)

### PR DESCRIPTION
**Pull request by rhuanjl**
Tidying up some CI points, improving neatness AND improving coverage.

**Changes include:**
- moving style check scripts to tools/StyleChecks
- Merging  `buildone.cmd` with `jenkins.buildone.cmd` and merging `testone.cmd` with `jenkins.testone.cmd`
- Moving windows tests onto `runtests.py`; as well as consolidating this means my change in #6444 to make non-existent tests count as failures will now work for windows
- Adding windows coverage for no-jit builds
- Enabling `slow` tests on windows test builds - still going to get done before posix builds
- Making macOS builds use ICU properly (they weren't)
- Running native tests on posix
- Getting rid of the name `jenkins` where possible
- Cleaning up/deleting a few other unused scripts
- Remove `exclude_jenkins` flag - was used for tests that fail on different timezones but runtests.py overrides TZ
- Remove `exclude_static` flag - was not used

I've also slightly re-done the list of builds after this we'll have:
**Posix Builds**
- Ubuntu 20 noJIT Debug
- Ubuntu 20 RelWithDebInfo
- Ubuntu 20 Release
- Ubuntu 18 RelWithDebInfo
- Ubuntu 18 Release
- macOS Debug with No ICU
- macOS RelWithDebInfo
- macOS Release

**Windows Builds**
- x86 Debug
- x86 noJIT Debug
- x86 Test
- x86 Release
- x64 Debug
- x64 Test
- x64 Release

The aim is to hit most things that could go wrong whilst avoiding too much repetition - Linux noJIT build is x64 hence having only an x86 noJIT build on windows; macOS and Linux builds are somewhat similar hence retaining noICU only for the macOS debug build. RelWithDebInfo test runs are measurably faster than Debug - moved the Ubuntu 18 run to that as not aware of anything Ubuntu 18 specific we're testing for with assertions.

Progress on: #6445 

Fix: #319

### CODE REVIEW

**Comment by rhuanjl** [comment]
Note I've not yet deleted Runtests.cmd or rl.exe - there are some extra test options in Runtests.cmd that I'd like to port to runtests.py first - we weren't using them and still aren't but I think they should be preserved for future use/experimented with.

(Whenever that is done the Contributing.md file would also need to be updated to advise the use of the runtests.py on windows)

Also it would be good in the long run to further consolidate OR remove all the CI related .cmd scripts but I have postponed this for now.

File: test/native-tests/test_native.sh [hunk 1]
```diff
@@ -90,15 +72,18 @@ done
...
 else
     export LD_LIBRARY_PATH=${LIB_DIR}/:$LD_LIBRARY_PATH
+    EXTENSION="so"
 fi
 
 RUN "test-shared-basic"
 
 # test python
-RUN_CMD "test-python" "python helloWorld.py ${BUILD_TYPE}"
+#RUN_CMD "test-python" "python helloWorld.py ${BUILD_TYPE} ${CH_DIR%/*}/libChakraCore.${EXTENSION}"
```
Comment (rhuanjl) [inline test/native-tests/test_native.sh:87]: The python test (which uses CDLL to load ChakraCore in a python script) is broken - I do not think this is a recent regression, the way it was called under the old CI it appears it could fail silently. I've commented out for now though should either fix or delete in the long run.

**Comment by rhuanjl** [comment]
One thing this doesn't do that I really wish it did is add arm support; not currently aware of any good solution for that.

**Comment by rhuanjl** [comment]
@ppenzin Do you think you could review this this week - it's fairly simple and the diff is actually quite small (large size is just one broken baseline I had to fix - I broke it before so was reverting my own change - it was previously not run as it was an exclude_jenkins test that I've enabled)

**Comment by ppenzin** [comment]
Yes, I should be able to. It is usually a matter of finding some uninterrupted time and just pushing through the review until the end :)

**Review by ppenzin — APPROVED** [review]
