### PR TITLE
Fix JsIsCallable

### LINKED ISSUE #6720: [JSRT API] Issue about JsIsCallable
`JsIsCallable` returns true if a class expression is passed - Was it intended to return true?

### PR DESCRIPTION
**Pull request by MadProbe**
This PR fixes JsIsCallable JSRT API function which was giving a false-positive when it was called on a class function (e.g. `class _ { }`).
Also this PR adds tests for JsIsCallable and JsIsConstructor, which were missing.

Closes #6720

### CODE REVIEW

File: lib/Jsrt/Core/JsrtCore.cpp [hunk 1]
```diff
@@ -1460,7 +1461,8 @@ CHAKRA_API JsIsCallable(_In_ JsValueRef object, _Out_ bool *isCallable)
         VALIDATE_INCOMING_OBJECT(object, scriptContext);
         PARAM_NOT_NULL(isCallable);
 
-        *isCallable = Js::JavascriptConversion::IsCallable(object);
+        *isCallable = (Js::JavascriptConversion::IsCallable(object) && !Js::JavascriptOperators::IsClassConstructor(object)) ||
+                       Js::VarIs<Js::JavascriptGeneratorFunction>(object);
```
Comment (rhuanjl) [inline lib/Jsrt/Core/JsrtCore.cpp]: `JavascriptOperators::IsClassConstructor` really should not be returning positive for generator functions - editing it so it doesn't; seems better than an extra check here - I tried offline and it doesn't appear to break anything...

**Comment by rhuanjl** [comment]
The tests look good and it definitely will be good to have this api working as advertised; just unsure about where to exclude generators - I think it should be over in `JavascriptOperators::IsClassConstructor`, can you just drop the `||` case there completely it seems to be doing nothing helpful.

File: lib/Jsrt/Core/JsrtCore.cpp (hunk 1 above)
Comment (MadProbe) [reply lib/Jsrt/Core/JsrtCore.cpp]: Maybe it's problem that is reproducible only at Windows machine, since i ran some tests that show that `IsClassConstructor` shows a false-positive:  
Format: (checks)  
(result with removed VarIs check) (checked value)
```
IsCallable: true, IsClassConstructor: false, VarIs<JavascriptGeneratorFunction>: false
true () => { }
IsCallable: true, IsClassConstructor: true, VarIs<JavascriptGeneratorFunction>: true
false async () => { }
IsCallable: true, IsClassConstructor: false, VarIs<JavascriptGeneratorFunction>: false
true function () { }
IsCallable: true, IsClassConstructor: true, VarIs<JavascriptGeneratorFunction>: true
false function* () { }
IsCallable: true, IsClassConstructor: true, VarIs<JavascriptGeneratorFunction>: true
false async function () { }
IsCallable: true, IsClassConstructor: true, VarIs<JavascriptGeneratorFunction>: true
false async function* () { }
```
But i agree that `VarIs` check is not required to fix the initial problem.

Comment (MadProbe) [reply lib/Jsrt/Core/JsrtCore.cpp]: So, should i move `VarIs` check to `IsClassConstructor`?

Comment (rhuanjl) [reply lib/Jsrt/Core/JsrtCore.cpp]: I thought the false positive was because of the second case over in JavascriptOperators::IsClassConstructor

As a generator function is neither a ScriptFunction nor an external function. BUT I can't see why we're checking for those there.

If we delete that second case should then be able to get rid of the extra check here.

**Review by rhuanjl — APPROVED** [review]

**Comment by rhuanjl** [comment]
Thank you for this, looks good to me.
