### PR TITLE
Throw `ERRBadAwait` instead of `ERRnoSemic` if applicable

### LINKED ISSUE #5103: Unhelpful Error Message - Should be missing 'async' keyword instead of Expected ';'
(Originally reported through VS forum, told to report here instead.)

If I have the following JavaScript Vue.js code in a UWP app:

```
    EventBus.$on("erase-history", (event) => {
        await clearCacheAsync().then(() => console.log("Cleared Cache"), (e) => console.error(`Error Clearing Cache ${e}`));
    });
```

Then I get an error message running my app:

    JavaScript critical error at line 94, column 19 in ms-appx://js/mycode.js \n\nSCRIPT1004: Expected ';'

(that's the line with the await on it)

The real problem is I'm missing the 'async' keyword on the line before:

    EventBus.$on("erase-history", async (event) => {

So my error message should be 'Expected async' to actually tell me what the real problem is. As otherwise, I look at semi-colons and I have nothing wrong.

### PR DESCRIPTION
**Pull request by ShortDevelopment**
## Issue
It might happen that a developer forgets to declare a function as `async` but still uses `await` as a keyword.
In this case the CC parser will just display a `ERRnoSemic` as seen in #5103.

## Changes
According to the proposal of @rhuanjl in https://github.com/chakra-core/ChakraCore/issues/5103#issuecomment-612573281 the parser now checks if the previous token was a `tkID` equal to `await`.
In that case the parser throws a `ERRBadAwait`.

---

Fixes #5103

### CODE REVIEW

**Comment by rhuanjl** [comment]
Thanks for the contribution, it would be nice to see this changed.

Unfortunately the test fails look legitimate to me, (as in this appears to have introduced a new bug) if you can work out what's gone wrong that would be great, if not I'll try and investigate on Monday or Tuesday.

**Comment by ShortDevelopment** [comment]
The Ubuntu 18 tests are just canceled. I gues Azure does not provide them as hosts any more.

To be honest: I've just ignored the Mac tests for now because there were so many failing tests and all other OSs did pass...

**Comment by ShortDevelopment** [comment]
@rhuanjl Comparing the CI output of a PR with "no code" and mine it seems like the failing tests might be unrelated to the changes in this PR

 - https://cirrus-ci.com/task/6543904518963200
 - https://cirrus-ci.com/task/6730463671222272

Both failed with
```
Total: passed 1382, failed 630
```

File: test/es7/asyncawait-syntax.js [hunk 1]
```diff
@@ -1,10 +1,14 @@
...
 // Copyright (C) Microsoft. All rights reserved.
+// Copyright (c) ChakraCore Project Contributors. All rights reserved.
 // Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
 //-------------------------------------------------------------------------------------------------------
 
 // ES6 Async Await tests -- verifies syntax of async/await
 
+// @ts-check
+/// <reference path="..\\UnitTestFramework\\UnitTestFramework.js" />
+
```
Comment (rhuanjl) [inline test/es7/asyncawait-syntax.js]: Please could you remove this I know it's useful within vscode but for now it's not standard in our source tree

**Comment by rhuanjl** [comment]
> @rhuanjl Comparing the CI output of a PR with "no code" and mine it seems like the failing tests might be unrelated to the changes in this PR
> 
> * https://cirrus-ci.com/task/6543904518963200
> * https://cirrus-ci.com/task/6730463671222272
> 
> Both failed with
> 
> ```
> Total: passed 1382, failed 630
> ```

Seems you were right, CI is sorted now, this PR looks good though I'd ideally not like to introduce the TS comments to our codebase.

File: test/es7/asyncawait-syntax.js (hunk 1 above)
Comment (ShortDevelopment) [reply test/es7/asyncawait-syntax.js]: Sure, but I'm afraid I've already added [some](https://github.com/search?q=repo%3Achakra-core%2FChakraCore%20%2F%2F%20%40ts-check&type=code) into CCs code-base 😅

**Comment by ShortDevelopment** [comment]
@rhuanjl Comments are removed

> Seems you were right, CI is sorted now

It's still a bit scary to have CI failing randomly

**Comment by rhuanjl** [comment]
> @rhuanjl Comments are removed
> 
> > Seems you were right, CI is sorted now
> 
> It's still a bit scary to have CI failing randomly

I think it was an issue ages ago that's been fixed in the meantime...

I'll gain additional confidence of that if it passes again now having already passed once before you removed the comments.
