### PR TITLE
Remove non-standard IE behaviour from Error constructor 

### LINKED ISSUE #5443: Error constructor with more than one argument
Hi everyone,

I found an inconsistence on Error() with more than one argument. 
According to [ES6 Error constructor](https://tc39.github.io/ecma262/#sec-error-message) the Error is called with only one argument (message).
The other engines returns the first argument, chakra returns the second argument.

Steps to reproduce:
```
try{
    throw new Error(null)
}catch (e){
    print(e)
}

try{
    throw new Error(null, 'test failed', 'another argument')
}catch (e){
    print(e)
}
```

Actual results:
Error: null
Error: test failed

Expected results:
Error: null
Error: null

V8, SpiderMonkey and JSC works as expected.

OS: Ubuntu 16.04 x86
chakra: 1.11.0.0-beta

### PR DESCRIPTION
**Pull request by rhuanjl**
The Error constructor in ChakraCore had support for an "error number" to do with how it was used in Internet Explorer - this was not compatible with spec.

Additionally there was a `description` property that was sometimes the same as the `message` property but was inconsistent.

Remove all of this.

Fix #5443

### CODE REVIEW

File: lib/Runtime/Library/JavascriptError.cpp [hunk 1]
```diff
@@ -132,6 +85,7 @@ namespace Js
         Var message = args.Info.Count > 1 ? args[1] : scriptContext->GetLibrary()->GetUndefined(); \
         return JavascriptError::NewInstance(function, pError, callInfo, newTarget, message); \
     }
+    NEW_ERROR(Error);
```
Comment (rhuanjl) [inline lib/Runtime/Library/JavascriptError.cpp:89]: Using NEW_ERROR here creates a NewErrorInstance method that behaves the same way that all the error subtypes constructors behave - see lines 78-87 for detail

**Comment by rhuanjl** [comment]
I was 50/50 on removing `error.description` as it could be breaking for someone BUT:
- removing it was much cleaner
- no other engine has it
- it was inconsistent (some errors had it and some didn't - whereas they all have `message` which other engines have AND when `description` was there it was the same as `message`)

**Comment by rhuanjl** [comment]
@ppenzin some low hanging fruit - not a priority BUT this spec violation was annoying. Please could you review when you have 10 minutes?

**Comment by rhuanjl** [comment]
Random side note: large number of force-pushes was because tests that use debug baselines aren't executed properly on Mac so had to open the PR to find some of those failing then fix and re-push etc.

Opened issue #6619 to follow up

**Review by ppenzin — APPROVED** [review]
