### PR TITLE
Fix Errors in Generator Jit for SlotArray and CopyProp Restores

### LINKED ISSUE #6678: Segmentation Fault in `Js::ScopeSlots::GetCount`
PoC:
```javascript
function main() {
async function v0(v1,v2,v3,v4) {
    for (let v8 = 0; v8 < 1337; v8++) {
        const v9 = class V9 {
            constructor(v11,v12,v13) {
                const v14 = !v8;
            }
            isView(v16,...v17) {
            }
            atan(v19) {
            }
            isFinite(v21,v22,v23) {
            }
        };
        const v24 = await v2;
    }
}
const v25 = v0();
CollectGarbage();
}
main();
```

backtrace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001032d02dd libChakraCore.dylib`Js::ScopeSlots::GetCount(this=0x00007ffeefbfe058) const at FunctionBody.h:3513:66
    frame #1: 0x0000000103683263 libChakraCore.dylib`Js::JavascriptOperators::OP_CloneScopeSlots(slotArray=0x0000000000000000, scriptContext=0x0000000908808258) at JavascriptOperators.cpp:7681:74
    frame #2: 0x000000090832044d
    frame #3: 0x0000000103c0d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #4: 0x00000001038c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x00000001007e67d0, entryPoint=(libChakraCore.dylib`NativeCodeGenerator::CheckCodeGenThunk(Js::RecyclableObject*, Js::CallInfo, ...)), args=Arguments @ 0x00007ffeefbfe238, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #5: 0x00000001038d2a47 libChakraCore.dylib`Js::JavascriptGenerator::CallGenerator(this=0x0000000908249060, data=0x00000001007e5030, resumeKind=Normal) at JavascriptGenerator.cpp:185:26
    frame #6: 0x0000000103883904 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnStepNextFunction(function=0x00000009082d2850, callInfo=(Count = 1, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:93:31
    frame #7: 0x0000000103883ae8 libChakraCore.dylib`Js::JavascriptAsyncFunction::AsyncSpawnStep(stepFunction=0x00000009082d2850, generator=0x0000000908249060, resolve=0x00000009082402a0, reject=0x0000000908240300) at JavascriptAsyncFunction.cpp:151:25
    frame #8: 0x0000000103884577 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction(function=0x00000009082d2770, callInfo=(Count = 2, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:130:5
    frame #9: 0x0000000103a873e6 libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(function=0x00000009082d70a0, callInfo=(Count = 1, Flags = CallFlags_None, unused = 0)) at JavascriptPromise.cpp:1074:37
    frame #10: 0x0000000103c0d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #11: 0x00000001038c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x00000009082d70a0, entryPoint=(libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(Js::RecyclableObject*, Js::CallInfo, ...) at JavascriptPromise.cpp:1037), args=Arguments @ 0x00007ffeefbfe9f0, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #12: 0x00000001038c65ff libChakraCore.dylib`Js::JavascriptFunction::CallRootFunctionInternal(obj=0x00000009082d70a0, args=Arguments @ 0x00007ffeefbfea60, scriptContext=0x0000000908808258, inScript=true) at JavascriptFunction.cpp:772:24
    frame #13: 0x00000001038c643c libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(obj=0x00000009082d70a0, args=<unavailable>, scriptContext=0x0000000908808258, inScript=true) at JavascriptFunction.cpp:717:15
    frame #14: 0x00000001038c63e1 libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(this=0x00000009082d70a0, args=<unavailable>, scriptContext=0x0000000908808258, inScript=true) at JavascriptFunction.cpp:832:16
    frame #15: 0x0000000102928525 libChakraCore.dylib`JsCallFunction::$_67::operator(this=0x00007ffeefbfeed0, scriptContext=0x0000000908808258, _actionEntryPopper=0x00007ffeefbfeeb0)(Js::ScriptContext*, TTD::TTDJsRTActionResultAutoRecorder&) const at Jsrt.cpp:2842:41
    frame #16: 0x0000000102927eb4 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(this=0x00007ffeefbfee68, scriptContext=0x0000000908808258)::'lambda'(Js::ScriptContext*)::operator()(Js::ScriptContext*) const at JsrtInternal.h:237:16
    frame #17: 0x0000000102927884 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::'lambda'(Js::ScriptContext*)>(fn=(anonymous class) @ 0x00007ffeefbfee68) at JsrtInternal.h:192:23
    frame #18: 0x00000001028e3d46 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(fn=(anonymous class) @ 0x00007ffeefbfeed0) at JsrtInternal.h:235:27
    frame #19: 0x00000001028e3d09 libChakraCore.dylib`::JsCallFunction(function=0x00000009082d70a0, args=0x00007ffeefbfefa0, cargs=1, result=0x00007ffeefbfef98) at Jsrt.cpp:2804:12
    frame #20: 0x000000010000bdeb ch`ChakraRTInterface::JsCallFunction(function=0x00000009082d70a0, arguments=0x00007ffeefbfefa0, argumentCount=1, result=0x00007ffeefbfef98) at ChakraRtInterface.h:416:149
    frame #21: 0x000000010001b35a ch`WScriptJsrt::CallbackMessage::CallFunction(this=0x0000000100307b70, fileName="/Users/cpang/Desktop/graduate/javascript/JS_Fuzzing/chakracore/crash2/Poc.js") at WScriptJsrt.cpp:1988:21
    frame #22: 0x000000010001b23d ch`WScriptJsrt::CallbackMessage::Call(this=0x0000000100307b70, fileName="/Users/cpang/Desktop/graduate/javascript/JS_Fuzzing/chakracore/crash2/Poc.js") at WScriptJsrt.cpp:1959:12
    frame #23: 0x000000010000543e ch`MessageQueue::ProcessAll(this=0x000000010770ae80, fileName="/Users/cpang/Desktop/graduate/javascript/JS_Fuzzing/chakracore/crash2/Poc.js") at MessageQueue.h:256:18
```

How to reproduce:

```
- ./build.sh -d -j
- ch -collectGarbage ./poc.js
```

The error code:
```c++
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001042d02dd libChakraCore.dylib`Js::ScopeSlots::GetCount(this=0x00007ffeefbfe058) const at FunctionBody.h:3513:66
   3510
   3511         size_t GetCount() const
   3512         {
-> 3513             return ::Math::PointerCastToIntegralTruncate<size_t>(slotArray[EncodedSlotCountSlotIndex]);
   3514         }
   3515
   3516         void SetCount(uint count)
```

### LINKED ISSUE #6679: Segmentation Fault in `amd64_CallFunction`
PoC:
```javascript
function main() {
  const v1 = `
      async function v2(v3,v4,v5,v6) {
              for (let v10 = 0; v10 < 1337; v10++) {
                          const v11 = await 1337;
                         }
                    }
                   const v12 = v2();
                    "w7tjpMAv1f";
            `;
  const v15 = eval(v1);
  CollectGarbage();
}
main();
```

backtrace:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x10)
    frame #0: 0x00000009084602af
->  0x9084602af: movq   0x10(%r15), %rax
    0x9084602b3: leaq   (%rax), %rcx
    0x9084602b6: movq   %rbx, (%rax)
    0x9084602b9: shrq   $0xc, %rcx

bt

  * frame #0: 0x00000009084602af
    frame #1: 0x000000010340d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #2: 0x00000001030c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x000000090825fd70, entryPoint=(libChakraCore.dylib`NativeCodeGenerator::CheckCodeGenThunk(Js::RecyclableObject*, Js::CallInfo, ...)), args=Arguments @ 0x00007ffeefbfe278, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #3: 0x00000001030d2a47 libChakraCore.dylib`Js::JavascriptGenerator::CallGenerator(this=0x0000000908249060, data=0x0001000000000539, resumeKind=Normal) at JavascriptGenerator.cpp:185:26
    frame #4: 0x0000000103083904 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnStepNextFunction(function=0x000000090840d5b0, callInfo=(Count = 1, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:93:31
    frame #5: 0x0000000103083ae8 libChakraCore.dylib`Js::JavascriptAsyncFunction::AsyncSpawnStep(stepFunction=0x000000090840d5b0, generator=0x0000000908249060, resolve=0x00000009082405a0, reject=0x0000000908240600) at JavascriptAsyncFunction.cpp:151:25
    frame #6: 0x0000000103084577 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction(function=0x000000090840d4d0, callInfo=(Count = 2, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:130:5
    frame #7: 0x00000001032873e6 libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(function=0x000000090840f3c0, callInfo=(Count = 1, Flags = CallFlags_None, unused = 0)) at JavascriptPromise.cpp:1074:37
    frame #8: 0x000000010340d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #9: 0x00000001030c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x000000090840f3c0, entryPoint=(libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(Js::RecyclableObject*, Js::CallInfo, ...) at JavascriptPromise.cpp:1037), args=Arguments @ 0x00007ffeefbfea30, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #10: 0x00000001030c65ff libChakraCore.dylib`Js::JavascriptFunction::CallRootFunctionInternal(obj=0x000000090840f3c0, args=Arguments @ 0x00007ffeefbfeaa0, scriptContext=0x0000000908808258, inScript=true) at JavascriptFunction.cpp:772:24
    frame #11: 0x00000001030c643c libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(obj=0x000000090840f3c0, args=<unavailable>, scriptContext=0x0000000908808258, inScript=true) at JavascriptFunction.cpp:717:15
    frame #12: 0x00000001030c63e1 libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(this=0x000000090840f3c0, args=<unavailable>, scriptContext=0x0000000908808258, inScript=true) at JavascriptFunction.cpp:832:16
    frame #13: 0x0000000102128525 libChakraCore.dylib`JsCallFunction::$_67::operator(this=0x00007ffeefbfef10, scriptContext=0x0000000908808258, _actionEntryPopper=0x00007ffeefbfeef0)(Js::ScriptContext*, TTD::TTDJsRTActionResultAutoRecorder&) const at Jsrt.cpp:2842:41
    frame #14: 0x0000000102127eb4 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(this=0x00007ffeefbfeea8, scriptContext=0x0000000908808258)::'lambda'(Js::ScriptContext*)::operator()(Js::ScriptContext*) const at JsrtInternal.h:237:16
    frame #15: 0x0000000102127884 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::'lambda'(Js::ScriptContext*)>(fn=(anonymous class) @ 0x00007ffeefbfeea8) at JsrtInternal.h:192:23
    frame #16: 0x00000001020e3d46 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(fn=(anonymous class) @ 0x00007ffeefbfef10) at JsrtInternal.h:235:27
    frame #17: 0x00000001020e3d09 libChakraCore.dylib`::JsCallFunction(function=0x000000090840f3c0, args=0x00007ffeefbfefe0, cargs=1, result=0x00007ffeefbfefd8) at Jsrt.cpp:2804:12
    frame #18: 0x000000010000bdeb ch`ChakraRTInterface::JsCallFunction(function=0x000000090840f3c0, arguments=0x00007ffeefbfefe0, argumentCount=1, result=0x00007ffeefbfefd8) at ChakraRtInterface.h:416:149
    frame #19: 0x000000010001b35a ch`WScriptJsrt::CallbackMessage::CallFunction(this=0x000000010030d590, fileName="./test_crashes.js") at WScriptJsrt.cpp:1988:21
    frame #20: 0x000000010001b23d ch`WScriptJsrt::CallbackMessage::Call(this=0x000000010030d590, fileName="./test_crashes.js") at WScriptJsrt.cpp:1959:12
    frame #21: 0x000000010000543e ch`MessageQueue::ProcessAll(this=0x00000009083040b0, fileName="./test_crashes.js") at MessageQueue.h:256:18
    frame #22: 0x0000000100004ba0 ch`RunScript(fileName="./test_crashes.js", fileContents="function main() {\n  const v1 = `\n      async function v2(v3,v4,v5,v6) {\n              for (let v10 = 0; v10 < 1337; v10++) {\n                          const v11 = await 1337;\n                                  }\n                                      }\n                                          const v12 = v2();\n                                              \"w7tjpMAv1f\";\n                                              `;\n  const v15 = eval(v1);\n  CollectGarbage();\n}\nmain();\n", fileLength=474, fileContentsFinalizeCallback=(ch`WScriptJsrt::FinalizeFree(void*) at WScriptJsrt.cpp:208), bufferValue=0x0000000000000000, fullPath="/Users/cpang/Desktop/graduate/javascript/ChakraCore/test_crashes.js", parserStateCache=0x0000000000000000)(void*), void*, char*, void*) at ch.cpp:480:17
    frame #23: 0x0000000100006f9e ch`ExecuteTest(fileName="./test_crashes.js") at ch.cpp:917:13
    frame #24: 0x000000010000734c ch`ExecuteTestWithMemoryCheck(fileName="./test_crashes.js") at ch.cpp:967:10
    frame #25: 0x0000000100007c89 ch`main(argc=3, c_argv=0x00007ffeefbff6f8) at ch.cpp:1274:20
    frame #26: 0x00007fff2034b621 libdyld.dylib`start + 1
    frame #27: 0x00007fff2034b621 libdyld.dylib`start + 1
```

How to reproduce:

```
- ./build.sh -d -j
- ./ch -collectGarbage
```

### LINKED ISSUE #6685: Assertion Error in `BuildBailInSymbolList`
PoC:

```
function main() {
do {
    function* v2(v3,v4,v5,...v6) {
        let v8 = 13.37;
        yield* -1728385604;
        const v13 = [1337,1337,1337,1337];
        const v14 = [Object,13.37,v13,1,1,Object,v13,1,1337];
        const v15 = v8++;
    }
    const v16 = v2();
} while (0 < 13.37);
}
main();

```

Backtrace:
```
* thread #5, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001024e6242 libChakraCore.dylib`LinearScan::GeneratorBailIn::BuildBailInSymbolList(this=0x0000700000d3a868, byteCodeUpwardExposedUses=0x000000090830ed20, upwardExposedUses=0x00000009081b7468, capturedValues=0x00000009081b7438) at LinearScan.cpp:5201:5
   5198	    }
   5199	    NEXT_BITSET_IN_SPARSEBV_EDITING;
   5200
-> 5201	    AssertOrFailFastMsg(unrestorableSymbols.IsEmpty(), "There are unrestorable backend-only symbols across yield points");
   5202	}
   5203
   5204	void LinearScan::GeneratorBailIn::InsertRestoreSymbols(
Target 0: (ch) stopped.
(lldb) bt
* thread #5, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00000001024e6242 libChakraCore.dylib`LinearScan::GeneratorBailIn::BuildBailInSymbolList(this=0x0000700000d3a868, byteCodeUpwardExposedUses=0x000000090830ed20, upwardExposedUses=0x00000009081b7468, capturedValues=0x00000009081b7438) at LinearScan.cpp:5201:5
    frame #1: 0x00000001024d5823 libChakraCore.dylib`LinearScan::GeneratorBailIn::GenerateBailIn(this=0x0000700000d3a868, bailInInstr=0x00000009081b7380) at LinearScan.cpp:5047:11
    frame #2: 0x00000001024cc5c6 libChakraCore.dylib`LinearScan::RegAlloc(this=0x0000700000d3a390) at LinearScan.cpp:293:38
    frame #3: 0x000000010226cc0d libChakraCore.dylib`Func::TryCodegen(this=0x0000700000d3b150) at Func.cpp:501:20
    frame #4: 0x000000010226bfef libChakraCore.dylib`Func::Codegen(alloc=0x0000700000d3b6e0, workItem=0x00000009081a1030, threadContextInfo=0x0000000907808258, scriptContextInfo=0x0000000101820058, outputData=0x0000700000d3bb20, epInfo=0x000000090812d120, runtimeInfo=0x0000000000000000, polymorphicInlineCacheInfo=0x00000009081809c0, codeGenAllocators=0x000000010100fc58, codeGenProfiler=0x0000000000000000, isBackgroundJIT=true) at Func.cpp:325:18
    frame #5: 0x00000001025bd931 libChakraCore.dylib`NativeCodeGenerator::CodeGen(this=0x0000000100508c48, pageAllocator=0x0000000100509418, workItemData=0x000000010040cf50, jitWriteData=0x0000700000d3bb20, foreground=false, epInfo=0x000000090812d120) at NativeCodeGenerator.cpp:890:9
    frame #6: 0x00000001025c00b8 libChakraCore.dylib`NativeCodeGenerator::CodeGen(this=0x0000000100508c48, pageAllocator=0x0000000100509418, workItem=0x000000010040cf28, foreground=false) at NativeCodeGenerator.cpp:1007:5
    frame #7: 0x00000001025c37f4 libChakraCore.dylib`NativeCodeGenerator::Process(this=0x0000000100508c48, job=0x000000010040cf30, threadData=0x00000001005093f8) at NativeCodeGenerator.cpp:1907:13
    frame #8: 0x0000000102678541 libChakraCore.dylib`JsUtil::BackgroundJobProcessor::Process(this=0x0000000100508db8, job=0x000000010040cf30, threadData=0x00000001005093f8) at Jobs.cpp:1037:36
    frame #9: 0x0000000102678b26 libChakraCore.dylib`JsUtil::BackgroundJobProcessor::Run(this=0x0000000100508db8, threadData=0x00000001005093f8) at Jobs.cpp:1135:44
    frame #10: 0x0000000102676062 libChakraCore.dylib`JsUtil::BackgroundJobProcessor::StaticThreadProc(lpParam=0x00000001005093f8) at Jobs.cpp:1319:20
    frame #11: 0x000000010209da83 libChakraCore.dylib`CorUnix::CPalThread::ThreadEntry(pvParam=0x0000000101821600) at pal_thread.cpp:1605:16
    frame #12: 0x00007fff20330950 libsystem_pthread.dylib`_pthread_start + 224
    frame #13: 0x00007fff2032c47b libsystem_pthread.dylib`thread_start + 15
```

It is reproducible both in `Relase` mode and `Debug` mode.

### LINKED ISSUE #6686: Assertion Error in `InsertRestoreSymbols`
PoC:
```javascript
function main() {
const v2 = [13.37,13.37,13.37,13.37,13.37];
async function v4(v5,v6,v7,v8) {
    const v10 = 0;
    for (let v14 = 0; v14 < 8; v14++) {
        v5["vEBD7ei78q"] = v14;
    }
    for (let v16 = 1; v16 < 1337; v16++) {
        const v17 = v2.__proto__;
        const v23 = [13.37,13.37,-2.2250738585072014e-308,13.37,13.37];
        const v24 = v23.length;
        const v25 = "-4294967296";
        const v26 = 7;
        function* v28(v29,v30,v31,...v32) {
        }
        let v33 = -2.2250738585072014e-308;
        const v34 = v28(v33,Object,Object);
        const v35 = 13.37;
        const v36 = 2384357829;
        const v37 = await "-4294967296";
        const v38 = --v33;
    }
    const v39 = 128;
}
const v40 = v4("vEBD7ei78q");
}
main();

```
backtrace:
```
* thread #5, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x00000001024e658c libChakraCore.dylib`LinearScan::GeneratorBailIn::InsertRestoreSymbols(this=0x0000700006fca868, byteCodeUpwardExposedUses=0x0000000907c16ba8, upwardExposedUses=0x0000000907c19b80, capturedValues=0x0000000907c19b50, insertionPoint=0x0000700006fc9a28) at LinearScan.cpp:5238:13
   5235	        if (lifetime->isSpilled)
   5236	        {
   5237	#if DBG
-> 5238	            AssertMsg(!dstSym->IsConst(), "We don't need to restore constant symbol that has already been spilled");
   5239	            // Supress assert in DbPostCheckLower
   5240	            dstSym->m_allocated = true;
   5241	#endif
Target 0: (ch) stopped.
(lldb) bt
* thread #5, stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
  * frame #0: 0x00000001024e658c libChakraCore.dylib`LinearScan::GeneratorBailIn::InsertRestoreSymbols(this=0x0000700006fca868, byteCodeUpwardExposedUses=0x0000000907c16ba8, upwardExposedUses=0x0000000907c19b80, capturedValues=0x0000000907c19b50, insertionPoint=0x0000700006fc9a28) at LinearScan.cpp:5238:13
    frame #1: 0x00000001024d5850 libChakraCore.dylib`LinearScan::GeneratorBailIn::GenerateBailIn(this=0x0000700006fca868, bailInInstr=0x0000000907c19a98) at LinearScan.cpp:5053:11
    frame #2: 0x00000001024cc5c6 libChakraCore.dylib`LinearScan::RegAlloc(this=0x0000700006fca390) at LinearScan.cpp:293:38
    frame #3: 0x000000010226cc0d libChakraCore.dylib`Func::TryCodegen(this=0x0000700006fcb150) at Func.cpp:501:20
    frame #4: 0x000000010226bfef libChakraCore.dylib`Func::Codegen(alloc=0x0000700006fcb6e0, workItem=0x0000000907c01030, threadContextInfo=0x0000000101009c58, scriptContextInfo=0x000000010100b458, outputData=0x0000700006fcbb20, epInfo=0x0000000907c7b000, runtimeInfo=0x0000000000000000, polymorphicInlineCacheInfo=0x0000000907c76da0, codeGenAllocators=0x000000090800ee58, codeGenProfiler=0x0000000000000000, isBackgroundJIT=true) at Func.cpp:325:18
    frame #5: 0x00000001025bd931 libChakraCore.dylib`NativeCodeGenerator::CodeGen(this=0x0000000100404a58, pageAllocator=0x0000000100405228, workItemData=0x00000001003108e0, jitWriteData=0x0000700006fcbb20, foreground=false, epInfo=0x0000000907c7b000) at NativeCodeGenerator.cpp:890:9
    frame #6: 0x00000001025c00b8 libChakraCore.dylib`NativeCodeGenerator::CodeGen(this=0x0000000100404a58, pageAllocator=0x0000000100405228, workItem=0x00000001003108b8, foreground=false) at NativeCodeGenerator.cpp:1007:5
    frame #7: 0x00000001025c37f4 libChakraCore.dylib`NativeCodeGenerator::Process(this=0x0000000100404a58, job=0x00000001003108c0, threadData=0x0000000100405208) at NativeCodeGenerator.cpp:1907:13
    frame #8: 0x0000000102678541 libChakraCore.dylib`JsUtil::BackgroundJobProcessor::Process(this=0x0000000100404bc8, job=0x00000001003108c0, threadData=0x0000000100405208) at Jobs.cpp:1037:36
    frame #9: 0x0000000102678b26 libChakraCore.dylib`JsUtil::BackgroundJobProcessor::Run(this=0x0000000100404bc8, threadData=0x0000000100405208) at Jobs.cpp:1135:44
    frame #10: 0x0000000102676062 libChakraCore.dylib`JsUtil::BackgroundJobProcessor::StaticThreadProc(lpParam=0x0000000100405208) at Jobs.cpp:1319:20
    frame #11: 0x000000010209da83 libChakraCore.dylib`CorUnix::CPalThread::ThreadEntry(pvParam=0x000000010100ca00) at pal_thread.cpp:1605:16
    frame #12: 0x00007fff20330950 libsystem_pthread.dylib`_pthread_start + 224
    frame #13: 0x00007fff2032c47b libsystem_pthread.dylib`thread_start + 15
```

It is reproducible both in `Relase` mode and `Debug` mode.

### LINKED ISSUE #6690: Invalid Memory Access in `GetTypeId`
PoC:
```javascript
function main() {
const v3 = [13.37,13.37,13.37,13.37];
const v5 = [1337,1337,1337,1337,1337];
const v6 = {__proto__:v5,a:"description",b:1337,c:undefined,length:1337,valueOf:v3};
async function v7(v8,v9,v10,v11,v12) {
    const v13 = `
        Object;
    `;
    for (const v15 in v6) {
        const v18 = (1000000.0).__proto__;
        for (const v19 in v15) {
            const v20 = {b:v13,e:v19,...v12,...v19,...1,...v11};
            const v21 = await v20;
        }
    }
    const v22 = v7();
}
const v23 = v7();
}
main();
```
Backtrace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001038edf1c libChakraCore.dylib`Js::Type::GetTypeId(this=0x0000000000000000) const at Type.h:48:50
   45
   46  	    public:
   47  	        static DWORD GetJavascriptLibraryOffset() { return offsetof(Type, javascriptLibrary); }
-> 48  	        inline TypeId GetTypeId() const { return typeId; }
   49  	        void SetTypeId(TypeId typeId) { this->typeId = typeId; }
   50  	        RecyclableObject* GetPrototype() const { return prototype; }
   51  	        JavascriptMethod GetEntryPoint() const { return entryPoint; }
Target 0: (ch) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001038edf1c libChakraCore.dylib`Js::Type::GetTypeId(this=0x0000000000000000) const at Type.h:48:50
    frame #1: 0x00000001038ede3d libChakraCore.dylib`Js::RecyclableObject::GetTypeId(this=0x0000000102be6828) const at RecyclableObject.inl:13:33
    frame #2: 0x0000000104662e35 libChakraCore.dylib`Js::JavascriptOperators::IsUndefinedOrNull(instance=0x0000000102be6828) at JavascriptOperators.cpp:11031:69
    frame #3: 0x000000010465b548 libChakraCore.dylib`Js::JavascriptOperators::GetPropertyObject(instance=0x0000000102be6828, scriptContext=0x000000010201f658, propertyObject=0x00007ffeefbfe088) at JavascriptOperators.cpp:2133:13
    frame #4: 0x0000000104697e10 libChakraCore.dylib`void* Js::JavascriptOperators::PatchGetValue<true, Js::InlineCache>(Js::FunctionBody*, Js::InlineCache*, unsigned int, void*, int) [inlined] void* Js::JavascriptOperators::PatchGetValueWithThisPtr<true, Js::InlineCache>(functionBody=0x0000000102d4c3e0, inlineCache=0x0000000102b8aef0, inlineCacheIndex=0, instance=0x0000000102be6828, propertyId=487, thisInstance=0x0000000102be6828) at JavascriptOperators.cpp:7950:22
    frame #5: 0x0000000104697d7d libChakraCore.dylib`void* Js::JavascriptOperators::PatchGetValue<true, Js::InlineCache>(functionBody=0x0000000102d4c3e0, inlineCache=0x0000000102b8aef0, inlineCacheIndex=0, instance=0x0000000102be6828, propertyId=487) at JavascriptOperators.cpp:7936
    frame #6: 0x0000000102e813bb
    frame #7: 0x0000000104c0d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #8: 0x00000001048c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x0000000102be6820, entryPoint=(0x0000000102e81000), args=Arguments @ 0x00007ffeefbfe358, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #9: 0x00000001048d2a47 libChakraCore.dylib`Js::JavascriptGenerator::CallGenerator(this=0x0000000102d49360, data=0x0000000102f17fe0, resumeKind=Normal) at JavascriptGenerator.cpp:185:26
    frame #10: 0x0000000104883904 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnStepNextFunction(function=0x0000000102f1b380, callInfo=(Count = 1, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:93:31
    frame #11: 0x0000000104883ae8 libChakraCore.dylib`Js::JavascriptAsyncFunction::AsyncSpawnStep(stepFunction=0x0000000102f1b380, generator=0x0000000102d49360, resolve=0x0000000102f1a060, reject=0x0000000102f1a0c0) at JavascriptAsyncFunction.cpp:151:25
    frame #12: 0x0000000104884577 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction(function=0x0000000102f1b2a0, callInfo=(Count = 2, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:130:5
    frame #13: 0x0000000104a873e6 libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(function=0x0000000102f1c1e0, callInfo=(Count = 1, Flags = CallFlags_None, unused = 0)) at JavascriptPromise.cpp:1074:37
    frame #14: 0x0000000104c0d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #15: 0x00000001048c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x0000000102f1c1e0, entryPoint=(libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(Js::RecyclableObject*, Js::CallInfo, ...) at JavascriptPromise.cpp:1037), args=Arguments @ 0x00007ffeefbfeb10, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #16: 0x00000001048c65ff libChakraCore.dylib`Js::JavascriptFunction::CallRootFunctionInternal(obj=0x0000000102f1c1e0, args=Arguments @ 0x00007ffeefbfeb80, scriptContext=0x000000010201f658, inScript=true) at JavascriptFunction.cpp:772:24
    frame #17: 0x00000001048c643c libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(obj=0x0000000102f1c1e0, args=<unavailable>, scriptContext=0x000000010201f658, inScript=true) at JavascriptFunction.cpp:717:15
    frame #18: 0x00000001048c63e1 libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(this=0x0000000102f1c1e0, args=<unavailable>, scriptContext=0x000000010201f658, inScript=true) at JavascriptFunction.cpp:832:16
    frame #19: 0x0000000103928525 libChakraCore.dylib`JsCallFunction::$_67::operator(this=0x00007ffeefbfeff0, scriptContext=0x000000010201f658, _actionEntryPopper=0x00007ffeefbfefd0)(Js::ScriptContext*, TTD::TTDJsRTActionResultAutoRecorder&) const at Jsrt.cpp:2842:41
    frame #20: 0x0000000103927eb4 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(this=0x00007ffeefbfef88, scriptContext=0x000000010201f658)::'lambda'(Js::ScriptContext*)::operator()(Js::ScriptContext*) const at JsrtInternal.h:237:16
    frame #21: 0x0000000103927884 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::'lambda'(Js::ScriptContext*)>(fn=(anonymous class) @ 0x00007ffeefbfef88) at JsrtInternal.h:192:23
    frame #22: 0x00000001038e3d46 libChakraCore.dylib`_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(fn=(anonymous class) @ 0x00007ffeefbfeff0) at JsrtInternal.h:235:27
    frame #23: 0x00000001038e3d09 libChakraCore.dylib`::JsCallFunction(function=0x0000000102f1c1e0, args=0x00007ffeefbff0c0, cargs=1, result=0x00007ffeefbff0b8) at Jsrt.cpp:2804:12
    frame #24: 0x000000010000bdeb ch`ChakraRTInterface::JsCallFunction(function=0x0000000102f1c1e0, arguments=0x00007ffeefbff0c0, argumentCount=1, result=0x00007ffeefbff0b8) at ChakraRtInterface.h:416:149
    frame #25: 0x000000010001b35a ch`WScriptJsrt::CallbackMessage::CallFunction(this=0x0000000102c04700, fileName="test.js") at WScriptJsrt.cpp:1988:21
    frame #26: 0x000000010001b23d ch`WScriptJsrt::CallbackMessage::Call(this=0x0000000102c04700, fileName="test.js") at WScriptJsrt.cpp:1959:12
    frame #27: 0x000000010000543e ch`MessageQueue::ProcessAll(this=0x00000001007088c0, fileName="test.js") at MessageQueue.h:256:18
    frame #28: 0x0000000100004ba0 ch`RunScript(fileName="test.js", fileContents="function main() {\nconst v3 = [13.37,13.37,13.37,13.37];\nconst v5 = [1337,1337,1337,1337,1337];\nconst v6 = {__proto__:v5,a:\"description\",b:1337,c:undefined,length:1337,valueOf:v3};\nasync function v7(v8,v9,v10,v11,v12) {\n    const v13 = `\n        Object;\n    `;\n    for (const v15 in v6) {\n        const v18 = (1000000.0).__proto__;\n        for (const v19 in v15) {\n            const v20 = {b:v13,e:v19,...v12,...v19,...1,...v11};\n            const v21 = await v20;\n        }\n    }\n    const v22 = v7();\n}\nconst v23 = v7();\n}\nmain();\n", fileLength=532, fileContentsFinalizeCallback=(ch`WScriptJsrt::FinalizeFree(void*) at WScriptJsrt.cpp:208), bufferValue=0x0000000000000000, fullPath="/Users/cpang/Desktop/graduate/javascript/ChakraCore/test.js", parserStateCache=0x0000000000000000)(void*), void*, char*, void*) at ch.cpp:480:17
    frame #29: 0x0000000100006f9e ch`ExecuteTest(fileName="test.js") at ch.cpp:917:13
    frame #30: 0x000000010000734c ch`ExecuteTestWithMemoryCheck(fileName="test.js") at ch.cpp:967:10
    frame #31: 0x0000000100007c89 ch`main(argc=2, c_argv=0x00007ffeefbff7d8) at ch.cpp:1274:20
    frame #32: 0x00007fff2034b621 libdyld.dylib`start + 1
    frame #33: 0x00007fff2034b621 libdyld.dylib`start + 1
```

How to reproduce it:
```
- ./build.sh -d -j
- ./ch poc.js
```

### LINKED ISSUE #6692: Invalid Memory Access in `OP_StSlot`
PoC:
```javascript
function main() {
async function v0(v1,v2,v3,v4,v5) {
    const v6 = `
        Object;
    `;
    for (const v9 in v2) {
        for (const v11 in v2) {
            const v12 = {b:v6,e:v11,...v5,...v11,...1,...v4};
            const v13 = await v12;
        }
        const v16 = [13.37,v9];
        const v18 = [1337,1337,1337,1337,Function];
        const v19 = {a:v18,c:v5,toString:v16};
        const v20 = {toString:13.37,a:v19};
        function v21(v22,v23) {
            const v25 = [13.37];
            const v27 = Reflect.get(v25,v20);
        }
    }
    const v28 = v0(RegExp,v1);
}
const v29 = v0();
}
main();
```
Backtrace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x00000001044c60e0 libChakraCore.dylib`Js::InterpreterStackFrame::OP_StSlot(this=0x0000000102af0c00, instance=0x0000000000000000, slotIndex=2, value=0x0000000102e508a0) at InterpreterStackFrame.cpp:9315:28
   9312	        // We emit OpCode::StSlot in the bytecode only for scope slot arrays, which are not recyclable objects.
   9313	        if (!PHASE_OFF(ClosureRangeCheckPhase, this->m_functionBody))
   9314	        {
-> 9315	            if ((uintptr_t)((Var*)instance)[ScopeSlots::EncodedSlotCountSlotIndex] <= (uintptr_t)(slotIndex - ScopeSlots::FirstSlotIndex))
   9316	            {
   9317	                Js::Throw::FatalInternalError();
   9318	            }
Target 0: (ch) stopped.
(lldb) bt 15
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x00000001044c60e0 libChakraCore.dylib`Js::InterpreterStackFrame::OP_StSlot(this=0x0000000102af0c00, instance=0x0000000000000000, slotIndex=2, value=0x0000000102e508a0) at InterpreterStackFrame.cpp:9315:28
    frame #1: 0x00000001044ff3df libChakraCore.dylib`Js::InterpreterStackFrame::ProcessProfiled(this=0x0000000102af0c00) at InterpreterHandler.inl:269:3
    frame #2: 0x00000001044938f4 libChakraCore.dylib`Js::InterpreterStackFrame::Process(this=0x0000000102af0c00) at InterpreterStackFrame.cpp:3472:20
    frame #3: 0x00000001044923fc libChakraCore.dylib`Js::InterpreterStackFrame::InterpreterHelper(function=0x0000000102ae67d0, args=ArgumentReader @ 0x00007ffeefbfe200, returnAddress=0x0000000102c80f92, addressOfReturnAddress=0x00007ffeefbfe248, asmJsReturn=0x0000000000000000) at InterpreterStackFrame.cpp:2153:40
    frame #4: 0x0000000104491480 libChakraCore.dylib`Js::InterpreterStackFrame::InterpreterThunk(layout=0x00007ffeefbfe260) at InterpreterStackFrame.cpp:1833:16
    frame #5: 0x0000000102c80f92
    frame #6: 0x0000000104c0d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #7: 0x00000001048c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x0000000102ae67d0, entryPoint=(libChakraCore.dylib`NativeCodeGenerator::CheckCodeGenThunk(Js::RecyclableObject*, Js::CallInfo, ...)), args=Arguments @ 0x00007ffeefbfe358, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #8: 0x00000001048d2a47 libChakraCore.dylib`Js::JavascriptGenerator::CallGenerator(this=0x0000000102c49120, data=0x0000000102e505e0, resumeKind=Normal) at JavascriptGenerator.cpp:185:26
    frame #9: 0x0000000104883904 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnStepNextFunction(function=0x0000000102e4d690, callInfo=(Count = 1, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:93:31
    frame #10: 0x0000000104883ae8 libChakraCore.dylib`Js::JavascriptAsyncFunction::AsyncSpawnStep(stepFunction=0x0000000102e4d690, generator=0x0000000102c49120, resolve=0x0000000102c404e0, reject=0x0000000102c40540) at JavascriptAsyncFunction.cpp:151:25
    frame #11: 0x0000000104884577 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction(function=0x0000000102e4d5b0, callInfo=(Count = 2, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:130:5
    frame #12: 0x0000000104a873e6 libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(function=0x0000000102e4a5f0, callInfo=(Count = 1, Flags = CallFlags_None, unused = 0)) at JavascriptPromise.cpp:1074:37
    frame #13: 0x0000000104c0d15e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #14: 0x00000001048c62db libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x0000000102e4a5f0, entryPoint=(libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(Js::RecyclableObject*, Js::CallInfo, ...) at JavascriptPromise.cpp:1037), args=Arguments @ 0x00007ffeefbfeb10, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
```

How to reproduce it:
```
- ./build.sh -d -j
- ch poc.js
```

### LINKED ISSUE #6697: Invalid Memory Access in `IsFunctionParsed`
PoC:
```javascript
function main() {
const v2 = async (v3,v4,v5) => {
    for (const v7 in "pS1LFZI9uc") {
        for (const v8 in v5) {
            const v11 = String();
            const v12 = eval(v11);
            const v13 = await "IJ8FcfXm6Z";
        }
    }
};
const v15 = v2(Symbol,Symbol,"NEGATIVE_INFINITY");
}
main();
```

Backtrace:
```
(gdb) bt
#0  0x00007f6efdb918fc in ?? ()
#1  0x00007ffd7a3a56f0 in ?? ()
#2  0x000056205352a46a in Js::ParseableFunctionInfo::IsFunctionParsed (this=0x1000000000000) at /src/chakracore/lib/Runtime/./Base/FunctionBody.h:1733
#3  Js::FunctionProxy::IsFunctionBody (this=<optimized out>) at /src/chakracore/lib/Runtime/Base/FunctionBody.cpp:168
#4  0x00005620556376ae in amd64_CallFunction () at /src/chakracore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#5  0x0000562054b94f98 in Js::JavascriptGenerator::CallGenerator (this=<optimized out>, data=<optimized out>, resumeKind=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptGenerator.cpp:185
#6  0x0000562054b062d9 in Js::JavascriptAsyncFunction::AsyncSpawnStep (stepFunction=0x7f6efdad3930, generator=0x7f6f008d3060, resolve=0x7f6f008f36c0, reject=0x7f6f008f3720)
    at /src/chakracore/lib/Runtime/Library/JavascriptAsyncFunction.cpp:151
#7  0x0000562054b08a68 in Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction (function=<optimized out>, callInfo=...) at /src/chakracore/lib/Runtime/Library/JavascriptAsyncFunction.cpp:130
#8  0x00005620552df2f6 in Js::JavascriptPromise::EntryReactionTaskFunction (function=<optimized out>, callInfo=...) at /src/chakracore/lib/Runtime/Library/JavascriptPromise.cpp:1074
#9  0x00005620556376ae in amd64_CallFunction () at /src/chakracore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#10 0x0000562054b71f37 in Js::JavascriptFunction::CallRootFunctionInternal (obj=<optimized out>, args=..., scriptContext=<optimized out>, inScript=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:772
#11 0x0000562054b716ed in Js::JavascriptFunction::CallRootFunction (obj=<optimized out>, scriptContext=<optimized out>, inScript=true, args=...) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:717
#12 Js::JavascriptFunction::CallRootFunction (this=<optimized out>, args=..., scriptContext=<optimized out>, inScript=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:832
#13 0x0000562052f2d7c8 in JsCallFunction::$_67::operator() (_actionEntryPopper=..., this=<optimized out>, scriptContext=<optimized out>) at /src/chakracore/lib/Jsrt/Jsrt.cpp:2842
#14 _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}::operator()(Js::ScriptContext*) const (this=<optimized out>, scriptContext=<optimized out>)
    at /src/chakracore/lib/Jsrt/JsrtInternal.h:237
#15 ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}>(_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}) (fn=...) at /src/chakracore/lib/Jsrt/JsrtInternal.h:192
#16 ContextAPIWrapper<false, JsCallFunction::$_67> (fn=...) at /src/chakracore/lib/Jsrt/JsrtInternal.h:235
#17 JsCallFunction (function=0x7f6efdad5640, args=0x7ffd7a3a6260, cargs=1, result=0x7ffd7a3a6280) at /src/chakracore/lib/Jsrt/Jsrt.cpp:2804
#18 0x0000562052d34282 in ChakraRTInterface::JsCallFunction (function=0x7f6efdad5640, arguments=<optimized out>, argumentCount=1, result=0x7ffd7a3a6280) at /src/chakracore/bin/ch/ChakraRtInterface.h:416
#19 WScriptJsrt::CallbackMessage::CallFunction (this=0x7ffd7a3a6280, fileName=<optimized out>) at /src/chakracore/bin/ch/WScriptJsrt.cpp:1993
#20 0x0000562052d0692e in MessageQueue::ProcessAll (this=<optimized out>, fileName=<optimized out>) at /src/chakracore/bin/ch/MessageQueue.h:256
#21 RunScript (fileName=0x606000000200 "IsFunctionParsed.js",
    fileContents=0x613000000200 "function main() {\nconst v2 = async (v3,v4,v5) => {\n    for (const v7 in \"pS1LFZI9uc\") {\n        for (const v8 in v5) {\n", ' ' <repeats 12 times>, "const v11 = String();\n", ' ' <repeats 12 times>, "const v12 = eval(v11);\n", ' ' <repeats 12 times>..., fileLength=140726654100624, fileContentsFinalizeCallback=0x562052d1fed0 <WScriptJsrt::FinalizeFree(void*)>, bufferValue=0x0, fullPath=<optimized out>,
    parserStateCache=<optimized out>) at /src/chakracore/bin/ch/ch.cpp:605
#22 0x0000562052d0ab65 in ExecuteTest (fileName=0x606000000200 "IsFunctionParsed.js") at /src/chakracore/bin/ch/ch.cpp:1152
#23 0x0000562052d0c029 in ExecuteTestWithMemoryCheck (fileName=0x562058a47b30 "") at /src/chakracore/bin/ch/ch.cpp:1203
#24 main (argc=<optimized out>, c_argv=<optimized out>) at /src/chakracore/bin/ch/ch.cpp:1538
```

How to reproduce:
```bash
- ./build.sh -j -d
- ch poc.js
```

### LINKED ISSUE #6698: Invalid Memory Access in `ConcatString`
PoC:
```javascript
function main() {
const v0 = "symbol";
const v4 = {constructor:Uint32Array,e:1337,length:13.37};
const v6 = [9007199254740991,9007199254740991,9007199254740991];
const v7 = Uint8ClampedArray;
async function v8(v9,v10,v11,v12) {
    for (let v16 = 0; v16 < 1337; v16++) {
        const v17 = [v16];
        const v18 = await v10;
        const v19 = v10 instanceof Uint32Array;
        const v21 = {set:v18};
        const v23 = Object.defineProperty(v4,3,v21);
    }
}
const v24 = v8();
}
main();
```

Backtrace:
```
(gdb) bt
#0  0x000055ca55a3ed04 in vtable for Js::ConcatString ()
#1  0x00007ffdd1058600 in ?? ()
#2  0x000055ca51e65176 in Js::JavascriptOperators::GetProperty_InternalSimple (instance=0x7f69cc4f9320, object=0x7f69cc4f9320, propertyId=400, value=0x7ffdd1058600, requestContext=0x622000000158)
    at /src/chakracore/lib/Runtime/Language/JavascriptOperators.cpp:1843
#3  0x000055ca51ed05ef in Js::JavascriptOperators::GetPropertyNoCache (instance=<optimized out>, propertyObject=0x7f69cc4f9320, propertyId=400, value=0x7ffdd1058600, requestContext=<optimized out>)
    at /src/chakracore/lib/Runtime/Language/JavascriptOperators.cpp:11325
#4  Js::JavascriptOperators::GetPropertyNoCache (instance=0x7f69cc4f9320, propertyId=400, value=0x7ffdd1058600, requestContext=<optimized out>) at /src/chakracore/lib/Runtime/Language/JavascriptOperators.cpp:11320
#5  Js::JavascriptOperators::ToPropertyDescriptorForGenericObjects (propertySpec=0x7f69cc4f9320, descriptor=0x7ffdd10587c0, scriptContext=<optimized out>) at /src/chakracore/lib/Runtime/Language/JavascriptOperators.cpp:9703
#6  0x000055ca51ed220c in Js::JavascriptOperators::ToPropertyDescriptor (propertySpec=0x7f69cc4f9320, descriptor=0x7ffdd10587c0, scriptContext=<optimized out>) at /src/chakracore/lib/Runtime/Language/JavascriptOperators.cpp:9757
#7  0x000055ca52aacc1d in Js::JavascriptObject::EntryDefineProperty (function=<optimized out>, callInfo=...) at /src/chakracore/lib/Runtime/Library/JavascriptObject.cpp:1307
#8  0x00007f69cc5b1523 in ?? ()
#9  0x00007f69cf419940 in ?? ()
#10 0x0000000002000004 in ?? ()
#11 0x00007f69cf426f00 in ?? ()
#12 0x00007f69cf471e70 in ?? ()
#13 0x0001000000000003 in ?? ()
#14 0x00007f69cc4f9320 in ?? ()
#15 0x00007ffdd1058960 in ?? ()
#16 0x000055ca52cde8b1 in Js::ScriptFunction::UpdateThunkEntryPoint (this=0x7f69cf475030, entryPointInfo=<optimized out>, entryPoint=0x10000000000ef) at /src/chakracore/lib/Runtime/Library/ScriptFunction.cpp:309
#17 0x000055ca52e496ae in amd64_CallFunction () at /src/chakracore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#18 0x000055ca523a6f98 in Js::JavascriptGenerator::CallGenerator (this=<optimized out>, data=<optimized out>, resumeKind=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptGenerator.cpp:185
#19 0x000055ca523182d9 in Js::JavascriptAsyncFunction::AsyncSpawnStep (stepFunction=0x7f69cc4f3ee0, generator=0x7f69cf413060, resolve=0x7f69cf433300, reject=0x7f69cf433360)
    at /src/chakracore/lib/Runtime/Library/JavascriptAsyncFunction.cpp:151
#20 0x000055ca5231aa68 in Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction (function=<optimized out>, callInfo=...) at /src/chakracore/lib/Runtime/Library/JavascriptAsyncFunction.cpp:130
#21 0x000055ca52af12f6 in Js::JavascriptPromise::EntryReactionTaskFunction (function=<optimized out>, callInfo=...) at /src/chakracore/lib/Runtime/Library/JavascriptPromise.cpp:1074
#22 0x000055ca52e496ae in amd64_CallFunction () at /src/chakracore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#23 0x000055ca52383f37 in Js::JavascriptFunction::CallRootFunctionInternal (obj=<optimized out>, args=..., scriptContext=<optimized out>, inScript=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:772
#24 0x000055ca523836ed in Js::JavascriptFunction::CallRootFunction (obj=<optimized out>, scriptContext=<optimized out>, inScript=true, args=...) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:717
#25 Js::JavascriptFunction::CallRootFunction (this=<optimized out>, args=..., scriptContext=<optimized out>, inScript=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:832
#26 0x000055ca5073f7c8 in JsCallFunction::$_67::operator() (_actionEntryPopper=..., this=<optimized out>, scriptContext=<optimized out>) at /src/chakracore/lib/Jsrt/Jsrt.cpp:2842
#27 _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}::operator()(Js::ScriptContext*) const (this=<optimized out>, scriptContext=<optimized out>)
    at /src/chakracore/lib/Jsrt/JsrtInternal.h:237
#28 ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}>(_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}) (fn=...) at /src/chakracore/lib/Jsrt/JsrtInternal.h:192
#29 ContextAPIWrapper<false, JsCallFunction::$_67> (fn=...) at /src/chakracore/lib/Jsrt/JsrtInternal.h:235
#30 JsCallFunction (function=0x7f69cc4fa0a0, args=0x7ffdd1059420, cargs=1, result=0x7ffdd1059440) at /src/chakracore/lib/Jsrt/Jsrt.cpp:2804
#31 0x000055ca50546282 in ChakraRTInterface::JsCallFunction (function=0x7f69cc4fa0a0, arguments=<optimized out>, argumentCount=1, result=0x7ffdd1059440) at /src/chakracore/bin/ch/ChakraRtInterface.h:416
#32 WScriptJsrt::CallbackMessage::CallFunction (this=0x7ffdd1059440, fileName=<optimized out>) at /src/chakracore/bin/ch/WScriptJsrt.cpp:1993
#33 0x000055ca5051892e in MessageQueue::ProcessAll (this=<optimized out>, fileName=<optimized out>) at /src/chakracore/bin/ch/MessageQueue.h:256
#34 RunScript (fileName=0x604000000710 "ConcatString.js",
    fileContents=0x615000000d00 "function main() {\nconst v0 = \"symbol\";\nconst v4 = {constructor:Uint32Array,e:1337,length:13.37};\nconst v6 = [9007199254740991,9007199254740991,9007199254740991];\nconst v7 = Uint8ClampedArray;\nasync fu"..., fileLength=140728110257744, fileContentsFinalizeCallback=0x55ca50531ed0 <WScriptJsrt::FinalizeFree(void*)>, bufferValue=0x0, fullPath=<optimized out>, parserStateCache=<optimized out>) at /src/chakracore/bin/ch/ch.cpp:605
#35 0x000055ca5051cb65 in ExecuteTest (fileName=0x604000000710 "ConcatString.js") at /src/chakracore/bin/ch/ch.cpp:1152
#36 0x000055ca5051e029 in ExecuteTestWithMemoryCheck (fileName=0x7f69cc4f9320 "\320\036G\317i\177") at /src/chakracore/bin/ch/ch.cpp:1203
#37 main (argc=<optimized out>, c_argv=<optimized out>) at /src/chakracore/bin/ch/ch.cpp:1538
```

How to reproduce it:
```bash
- ./build.sh -d -j
- ch poc.js
```

### LINKED ISSUE #6699: Invalid Memory Access in `WBSetBit`
PoC:
```javascript
function main() {
const v2 = async (v3,v4,...v5) => {
};
const v9 = {call:v2,has:eval};
async function v10(v11,v12,v13,v14) {
    for (let v17 = 0; v17 < 257; v17++) {
        const v22 = [13.37,13.37,13.37,4294967296,13.37];
        const v23 = [13.37];
        const v24 = ["s2cshfCfBy"];
        const v25 = {__proto__:v24,a:"-4294967297",d:v24,e:v22,length:4294967296,toString:arguments,valueOf:v23};
        const v26 = await v9;
    }
    const v30 = [257,0,10,9007199254740992];
}
const v31 = v10();
}
main();
```
Backtrace:
```
(gdb) bt
#0  0x00007fd77b8014ef in ?? ()
#1  0x00000ffaef74fc61 in ?? ()
#2  0x00007fd77ba865d0 in ?? ()
#3  0x00000ffaef75cd0f in ?? ()
#4  0x00007fd77bae6870 in ?? ()
#5  0x00007fd77b801000 in ?? ()
#6  0x00007fd77b837000 in ?? ()
#7  0x00007fffb6663260 in ?? ()
#8  0x000055d8df6fd899 in Memory::Recycler::WBSetBit (addr=0x7fd77ba8a000 "") at /src/chakracore/lib/Common/Memory/Recycler.cpp:9227
#9  0x000055d8e19176ae in amd64_CallFunction () at /src/chakracore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#10 0x000055d8e0e74f98 in Js::JavascriptGenerator::CallGenerator (this=<optimized out>, data=<optimized out>, resumeKind=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptGenerator.cpp:185
#11 0x000055d8e0de62d9 in Js::JavascriptAsyncFunction::AsyncSpawnStep (stepFunction=0x7fd778b3b690, generator=0x7fd77ba83060, resolve=0x7fd77baa3300, reject=0x7fd77baa3360) at /src/chakracore/lib/Runtime/Library/JavascriptAsyncFunction.cpp:151
#12 0x000055d8e0de8a68 in Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction (function=<optimized out>, callInfo=...) at /src/chakracore/lib/Runtime/Library/JavascriptAsyncFunction.cpp:130
#13 0x000055d8e15bf2f6 in Js::JavascriptPromise::EntryReactionTaskFunction (function=<optimized out>, callInfo=...) at /src/chakracore/lib/Runtime/Library/JavascriptPromise.cpp:1074
#14 0x000055d8e19176ae in amd64_CallFunction () at /src/chakracore/lib/Runtime/Library/amd64/JavascriptFunctionA.S:100
#15 0x000055d8e0e51f37 in Js::JavascriptFunction::CallRootFunctionInternal (obj=<optimized out>, args=..., scriptContext=<optimized out>, inScript=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:772
#16 0x000055d8e0e516ed in Js::JavascriptFunction::CallRootFunction (obj=<optimized out>, scriptContext=<optimized out>, inScript=true, args=...) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:717
#17 Js::JavascriptFunction::CallRootFunction (this=<optimized out>, args=..., scriptContext=<optimized out>, inScript=<optimized out>) at /src/chakracore/lib/Runtime/Library/JavascriptFunction.cpp:832
#18 0x000055d8df20d7c8 in JsCallFunction::$_67::operator() (_actionEntryPopper=..., this=<optimized out>, scriptContext=<optimized out>) at /src/chakracore/lib/Jsrt/Jsrt.cpp:2842
#19 _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}::operator()(Js::ScriptContext*) const (this=<optimized out>, scriptContext=<optimized out>) at /src/chakracore/lib/Jsrt/JsrtInternal.h:237
#20 ContextAPIWrapper_Core<false, _JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}>(_JsErrorCode ContextAPIWrapper<false, JsCallFunction::$_67>(JsCallFunction::$_67)::{lambda(Js::ScriptContext*)#1}) (fn=...) at /src/chakracore/lib/Jsrt/JsrtInternal.h:192
#21 ContextAPIWrapper<false, JsCallFunction::$_67> (fn=...) at /src/chakracore/lib/Jsrt/JsrtInternal.h:235
#22 JsCallFunction (function=0x7fd778b38870, args=0x7fffb6663da0, cargs=1, result=0x7fffb6663dc0) at /src/chakracore/lib/Jsrt/Jsrt.cpp:2804
#23 0x000055d8df014282 in ChakraRTInterface::JsCallFunction (function=0x7fd778b38870, arguments=<optimized out>, argumentCount=1, result=0x7fffb6663dc0) at /src/chakracore/bin/ch/ChakraRtInterface.h:416
#24 WScriptJsrt::CallbackMessage::CallFunction (this=0x7fffb6663dc0, fileName=<optimized out>) at /src/chakracore/bin/ch/WScriptJsrt.cpp:1993
#25 0x000055d8defe692e in MessageQueue::ProcessAll (this=<optimized out>, fileName=<optimized out>) at /src/chakracore/bin/ch/MessageQueue.h:256
#26 RunScript (fileName=0x6040000006d0 "WBSetBit.js",
    fileContents=0x616000000380 "function main() {\nconst v2 = async (v3,v4,...v5) => {\n};\nconst v9 = {call:v2,has:eval};\nasync function v10(v11,v12,v13,v14) {\n    for (let v17 = 0; v17 < 257; v17++) {\n        const v22 = [13.37,13.37"...,
    fileLength=140736253542352, fileContentsFinalizeCallback=0x55d8defffed0 <WScriptJsrt::FinalizeFree(void*)>, bufferValue=0x0, fullPath=<optimized out>, parserStateCache=<optimized out>) at /src/chakracore/bin/ch/ch.cpp:605
#27 0x000055d8defeab65 in ExecuteTest (fileName=0x6040000006d0 "WBSetBit.js") at /src/chakracore/bin/ch/ch.cpp:1152
#28 0x000055d8defec029 in ExecuteTestWithMemoryCheck (fileName=0x55d8e4e58660 "") at /src/chakracore/bin/ch/ch.cpp:1203
#29 main (argc=<optimized out>, c_argv=<optimized out>) at /src/chakracore/bin/ch/ch.cpp:1538
```

How to reproduce it:
```bash
- ./build.sh -d -j
- ch poc.js
```

### LINKED ISSUE #6705: Invalid Memory Access in `OP_LdSlot`
PoC:
```javascript
function main() {
const v2 = [13.37,1337,1337,1337,1337];
async function v3(v4,v5,v6,v7,v8) {
    const v9 = `
        v7;
    `;
    for (const v11 in v7) {
        for (const v13 in v5) {
            const v14 = {b:v9,e:v13,...v8,...v3,...1,...v7};
            const v15 = await v14;
        }
        function v16(v17) {
        }
        const v18 = v16;
        function v19(v20,v21) {
            v16 = v20;
        }
    }
    const v22 = v3(RegExp,v4,RegExp,v2);
}
const v23 = v3();
}
main();

```

Bactrace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x0000000102e1475c libChakraCore.dylib`Js::InterpreterStackFrame::OP_LdSlot(this=0x00000001006f7c00, instance=0x0000000000000000, slotIndex=2) at InterpreterStackFrame.cpp:9169:28
   9166	    {
   9167	        if (!PHASE_OFF(ClosureRangeCheckPhase, this->m_functionBody))
   9168	        {
-> 9169	            if ((uintptr_t)((Var*)instance)[ScopeSlots::EncodedSlotCountSlotIndex] <= (uintptr_t)(slotIndex - ScopeSlots::FirstSlotIndex))
   9170	            {
   9171	                Js::Throw::FatalInternalError();
   9172	            }
Target 0: (ch) stopped.
(lldb) bt 20
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x0000000102e1475c libChakraCore.dylib`Js::InterpreterStackFrame::OP_LdSlot(this=0x00000001006f7c00, instance=0x0000000000000000, slotIndex=2) at InterpreterStackFrame.cpp:9169:28
    frame #1: 0x0000000102d35799 libChakraCore.dylib`void* Js::InterpreterStackFrame::OP_LdInnerSlot<Js::OpLayoutDynamicProfile<Js::OpLayoutT_ElementSlotI2<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > __unaligned>(this=0x00000001006f7c00, slotArray=0x0000000000000000, playout=0x000000090824d0af)0> > > __unaligned const __unaligned*) at InterpreterStackFrame.cpp:9196:16
    frame #2: 0x0000000102d0674c libChakraCore.dylib`void* Js::InterpreterStackFrame::OP_ProfiledLdInnerSlot<Js::OpLayoutDynamicProfile<Js::OpLayoutT_ElementSlotI2<Js::LayoutSizePolicy<(Js::LayoutSize)0> > > __unaligned>(this=0x00000001006f7c00, slotArray=0x0000000000000000, playout=0x000000090824d0af)0> > > __unaligned const __unaligned*) at InterpreterStackFrame.cpp:9203:21
    frame #3: 0x0000000102cfef47 libChakraCore.dylib`Js::InterpreterStackFrame::ProcessProfiled(this=0x00000001006f7c00) at InterpreterHandler.inl:253:3
    frame #4: 0x0000000102c93804 libChakraCore.dylib`Js::InterpreterStackFrame::Process(this=0x00000001006f7c00) at InterpreterStackFrame.cpp:3472:20
    frame #5: 0x0000000102c9230c libChakraCore.dylib`Js::InterpreterStackFrame::InterpreterHelper(function=0x00000001006e6820, args=ArgumentReader @ 0x00007ffeefbfe1f0, returnAddress=0x0000000908260f92, addressOfReturnAddress=0x00007ffeefbfe238, asmJsReturn=0x0000000000000000) at InterpreterStackFrame.cpp:2153:40
    frame #6: 0x0000000102c91390 libChakraCore.dylib`Js::InterpreterStackFrame::InterpreterThunk(layout=0x00007ffeefbfe250) at InterpreterStackFrame.cpp:1833:16
    frame #7: 0x0000000908260f92
    frame #8: 0x000000010340d14e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #9: 0x00000001030c625b libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x00000001006e6820, entryPoint=(libChakraCore.dylib`NativeCodeGenerator::CheckCodeGenThunk(Js::RecyclableObject*, Js::CallInfo, ...)), args=Arguments @ 0x00007ffeefbfe348, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #10: 0x00000001030d29c7 libChakraCore.dylib`Js::JavascriptGenerator::CallGenerator(this=0x00000009082290c0, data=0x0000000908466820, resumeKind=Normal) at JavascriptGenerator.cpp:185:26
    frame #11: 0x0000000103083814 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnStepNextFunction(function=0x00000009084674d0, callInfo=(Count = 1, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:93:31
    frame #12: 0x00000001030839f8 libChakraCore.dylib`Js::JavascriptAsyncFunction::AsyncSpawnStep(stepFunction=0x00000009084674d0, generator=0x00000009082290c0, resolve=0x00000009082bf0c0, reject=0x00000009082bf120) at JavascriptAsyncFunction.cpp:151:25
    frame #13: 0x0000000103084487 libChakraCore.dylib`Js::JavascriptAsyncFunction::EntryAsyncSpawnCallStepFunction(function=0x00000009084673f0, callInfo=(Count = 2, Flags = CallFlags_Value, unused = 0)) at JavascriptAsyncFunction.cpp:130:5
    frame #14: 0x00000001032873d6 libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(function=0x0000000908469230, callInfo=(Count = 1, Flags = CallFlags_None, unused = 0)) at JavascriptPromise.cpp:1074:37
    frame #15: 0x000000010340d14e libChakraCore.dylib`amd64_CallFunction at JavascriptFunctionA.S:100
    frame #16: 0x00000001030c625b libChakraCore.dylib`void* Js::JavascriptFunction::CallFunction<true>(function=0x0000000908469230, entryPoint=(libChakraCore.dylib`Js::JavascriptPromise::EntryReactionTaskFunction(Js::RecyclableObject*, Js::CallInfo, ...) at JavascriptPromise.cpp:1037), args=Arguments @ 0x00007ffeefbfeb00, useLargeArgCount=false)(Js::RecyclableObject*, Js::CallInfo, ...), Js::Arguments, bool) at JavascriptFunction.cpp:1364:16
    frame #17: 0x00000001030c657f libChakraCore.dylib`Js::JavascriptFunction::CallRootFunctionInternal(obj=0x0000000908469230, args=Arguments @ 0x00007ffeefbfeb70, scriptContext=0x0000000101819658, inScript=true) at JavascriptFunction.cpp:772:24
    frame #18: 0x00000001030c63bc libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(obj=0x0000000908469230, args=<unavailable>, scriptContext=0x0000000101819658, inScript=true) at JavascriptFunction.cpp:717:15
    frame #19: 0x00000001030c6361 libChakraCore.dylib`Js::JavascriptFunction::CallRootFunction(this=0x0000000908469230, args=<unavailable>, scriptContext=0x0000000101819658, inScript=true) at JavascriptFunction.cpp:832:16
```

How to reproduce it:
```
- build.sh -d -j
- ./ch poc.js
```

### PR DESCRIPTION
**Pull request by rhuanjl**
## Issue 1 - Slot Array

The SlotArray is used to store variables that belong to local scopes (`let` and `const`), on an `InterpreterStackFrame` this is stored in a different location to other registers.

When resuming a jitted generator/async function after a yield/await point these local scopes must be restored BUT there is no logic to handle this restoration.

Instead immediately before the function is resumed in `CallGenerator()` copy the local scopes into "normal" reg slots that the jit can read from.

Notes:
1. this is only necessary if the function has already been partially executed (hence only do it if there is an Interpreter Stack Frame)
2. all Async functions, generator functions and AsyncGenerator functions go through CallGenerator - hence this is the right place for the fix
3. The jit is already trying to load these values from the location I'm now moving them to, see logic here:
https://github.com/chakra-core/ChakraCore/blob/c7f192ad1dd460fd5f4a19aef321135ed77d8931/lib/Backend/LinearScan.cpp#L5225-L5233
AND here:
https://github.com/chakra-core/ChakraCore/blob/master/lib/Backend/LinearScan.cpp#L5371
BUT was finding nothing - if the function begun in the interpreter it doesn't to write to this location, if it begun in the jit it's 0'd out when the function yields/awaits here:
https://github.com/chakra-core/ChakraCore/blob/c7f192ad1dd460fd5f4a19aef321135ed77d8931/lib/Backend/BailOut.cpp#L1742-L1748

Fix: #6678 
Fix: #6679
Fix: #6692 
Fix: #6690
Fix: #6697
Fix: #6698
Fix: #6699
Fix: #6705

## Issue 2 - Copy prop'd syms

A book keeping error was resulting in hitting a FailFast unnecessarily when setting up a restore for a copy prop'd sym after a yield.

Also, whether or not a copy prop sym should be restored was being checked using its Key; correct if restoring to Key BUT when restoring to Value need to check based on Value.

Note, I've added the full POC from issue 6686 as a new test file because reducing it proved difficult.

Fix: #6685
Fix: #6686

@bin2415 thanks for the report
@xuelanxu thanks for the report

### CODE REVIEW

**Comment by rhuanjl** [comment]
@nhat-nguyen this was an interesting bug - curious if you’d come across it at all?

File: lib/Runtime/ByteCode/ByteCodeEmitter.cpp [hunk 1]
```diff
@@ -1792,7 +1792,7 @@ void ByteCodeGenerator::FinalizeRegisters(FuncInfo* funcInfo, Js::FunctionBody*
         }
     }
 
-    // NOTE: The FB expects the yield reg to be the final non-temp.
+    // NOTE: The FunctionBody expects the yield reg to be the final non-temp.
```
Comment (rhuanjl) [inline lib/Runtime/ByteCode/ByteCodeEmitter.cpp:1795]: Ride-along comment improvement as I was tracking through where different registers go it took me a while to work out what an FB was

File: lib/Runtime/Library/JavascriptGenerator.cpp [hunk 2]
```diff
@@ -171,6 +172,18 @@ Var JavascriptGenerator::CallGenerator(Var data, ResumeYieldKind resumeKind)
...
+    if (this->frame)
+    {
+        // if the function already has a state it may be going to resume in the jit
+        // if so copy any innerScopes into registers jit can access
+        uint32 innerScopeCount = this->scriptFunction->GetFunctionBody()->GetInnerScopeCount();
+        for (uint32 i = 0; i < innerScopeCount; ++i)
+        {
+            Js::RegSlot reg = this->scriptFunction->GetFunctionBody()->GetFirstInnerScopeRegister() + i;
+            this->frame->SetNonVarReg(reg, this->frame->InnerScopeFromIndex(i));
+        }
```
Comment (rhuanjl) [inline lib/Runtime/Library/JavascriptGenerator.cpp:184]: This is effectively an inverse of lines 1742-1748 of BailOut.cpp.

NOTE - getting rid of the logic in BailOut.cpp would not be a sufficient fix as it's possible for a generator to start in the interpreter and transition to the Jit at a yield point

File: test/es6/generator-jit-bugs.js [hunk 3]
```diff
@@ -90,4 +90,51 @@ check(gen4.next().value, 1);
 check(gen4.next().value, 2);
 check(gen4.next().value, 3);
 
+title("Load Scope Slots in presence of for-in");
```
Comment (rhuanjl) [inline test/es6/generator-jit-bugs.js:95]: Note all these cases could be done as async functions (swap yield to await) - testing only as generators as internally the important code pathways are identical and doing it with generators means the test case doesn't have to wait for promises to resolve.

File: lib/Backend/LinearScan.cpp [hunk 4]
```diff
@@ -5135,8 +5135,10 @@ void LinearScan::GeneratorBailIn::BuildBailInSymbolList(
 
         if (unrestorableSymbols.TestAndClear(value->m_id))
         {
-            if (this->NeedsReloadingSymWhenBailingIn(copyPropSym.Key()))
+            if (this->NeedsReloadingSymWhenBailingIn(copyPropSym.Value()))
```
Comment (rhuanjl) [inline lib/Backend/LinearScan.cpp:5138]: Compare with lines 5146-5150.

Important point is we must check if this Sym needs reloading based on its BackEndId (see line 5140 compared with line 5148.

File: lib/Backend/LinearScan.cpp [hunk 5]
```diff
@@ -5135,8 +5135,10 @@ void LinearScan::GeneratorBailIn::BuildBailInSymbolList(
...
             {
+                // we're restoring this sym based on the value also remove the key from unrestorableSymbols
+                unrestorableSymbols.Clear(key->m_id);
```
Comment (rhuanjl) [inline lib/Backend/LinearScan.cpp:5141]: We're restoring from the Value, get rid of the key as well (otherwise hit a book keeping failfast)

File: lib/Backend/LinearScan.cpp [hunk 6]
```diff
@@ -5135,13 +5135,13 @@ void LinearScan::GeneratorBailIn::BuildBailInSymbolList(
...
         {
-            if (this->NeedsReloadingSymWhenBailingIn(copyPropSym.Key()))
+            if (this->NeedsReloadingSymWhenBailingIn(copyPropSym.Value()))
             {
                 BailInSymbol bailInSym(key->m_id /* fromByteCodeRegSlot */, value->m_id /* toBackendId */);
                 bailInSymbols->PrependNode(this->func->m_alloc, bailInSym);
             }
         }
-        else if (unrestorableSymbols.TestAndClear(key->m_id))
+        if (unrestorableSymbols.TestAndClear(key->m_id))
```
Comment (rhuanjl) [inline lib/Backend/LinearScan.cpp:5144]: Sometimes both the 'value' and 'key' appear in the unrestorableSymbols list; therefore always check both.

File: lib/Backend/LinearScan.cpp [hunk 7]
```diff
@@ -3339,7 +3339,7 @@ LinearScan::KillImplicitRegs(IR::Instr *instr)
         return;
     }
 
-    if (instr->m_opcode == Js::OpCode::Yield)
+    if (instr->m_opcode == Js::OpCode::GeneratorBailInLabel)
```
Comment (rhuanjl) [inline lib/Backend/LinearScan.cpp:3342]: The OpCode "Yield" is removed in the IRBuilder, converted into a sequence of instructions handle both the pausing of the function and the resumption.

The GeneratorBailInLabel is the resume marker and hence the condition to check for spilling registers.

**Review by ppenzin — APPROVED** [review]
