### PR TITLE
Throw `TypeError` on `Object.assign` with readonly property

### LINKED ISSUE #6523: An issue about Object.assign
###### Version

chakra-1_11_22

###### Test case

```js
var o = {
    get x(){}
}; 
Object. assign(o,o);
```

###### Execution steps

```js
./ChakraCore/out/Debug/ch testcase.js
```

###### Output

```

```

###### Expected behavior

```js
TypeError: Cannot set property x of [object Object] which has only a getter
```

###### Description

When the source object and target object of `Object.assign` are both objects that only contain getter properties, other engines (such as v8, spiderMonkey, JavaScriptCore, etc.) threw a `TypeError `exception, but chakra passed it normally.

### PR DESCRIPTION
**Pull request by ShortDevelopment**
Assigning values to read-only properties via `Object.assign` should throw a `TypeError` but it didn't.
https://tc39.es/ecma262/#sec-set-o-p-v-throw

I'm not sure if / in how fare this problem could exist for similar apis.

@rhuanjl 

Fix #6523

### CODE REVIEW

File: lib/Runtime/Language/JavascriptOperators.cpp [hunk 1]
```diff
@@ -2712,6 +2712,12 @@ using namespace Js;
         {
             if ((flags & Accessor) == Accessor)
             {
+                if (IsUndefinedAccessor(setterValueOrProxy, requestContext)
+                    && JavascriptError::ThrowCantAssign(propertyOperationFlags, requestContext, propertyId))
+                {
+                    *result = TRUE;
+                    return true;
+                }
                 if (JavascriptError::ThrowIfStrictModeUndefinedSetter(propertyOperationFlags, setterValueOrProxy, requestContext) ||
```
Comment (rhuanjl) [inline lib/Runtime/Language/JavascriptOperators.cpp]: Unless I'm misreading this, this means you check for an undefined accessor twice (once as part of `IsUndefinedAccessor` and another as part of `ThrowIfStrictModeUndefinedSetter`) can you refactor to avoid doing the same check twice - or at least not repeat it if it came back true?

**Comment by rhuanjl** [comment]
Thanks for the submission. I've added one comment above - but I will need to look in more detail later in the week - I have limited time now and this isn't the fix I was expecting - though clearly looks like it works, I'll need to go over it in a bit more detail to understand.

File: lib/Runtime/Language/JavascriptOperators.cpp (hunk 1 above)
Comment (ShortDevelopment) [reply lib/Runtime/Language/JavascriptOperators.cpp]: That's true, but it already does so one line further:
https://github.com/chakra-core/ChakraCore/blob/428b1a350a0b9596b851fa8167a7c3c3a65cad86/lib/Runtime/Language/JavascriptOperators.cpp#L2721-L2722
I should maybe rewrite both to also ensure the correct error.

**Review by rhuanjl — APPROVED** [review]
