### PR TITLE
Remove getVarDate, VariantDate and WinRTDate + cleanup

### LINKED ISSUE #6534: Assertion failure in JSONStringifier.cpp caused by incorrect type checking
Hello, running following code in ch1.11.24(debug), an assertion will be thrown. 
```
vdate = new Date(1234567890123).getVarDate();
JSON.stringify(vdate, true);
```
output:
```
ASSERTION 28300: (c:\users\sunlili\documents\workspace\jsenginesfordebug\chakracore-1.11.24\lib\runtime\library\jsonstringifier.cpp, line 745) UNREACHED
 Failure: ((0))
FATAL ERROR: ch.exe failed due to exception code c0000420
```
tmp

`vdate` is a Js::JavascriptVariantDate object, whose typeID is 10. Since TypeIds_VariantDate (10) < TypeIds_LastJavascriptPrimitiveType (21), it isn't be treated as object type in `JavascriptOperators::IsObject(_In_ RecyclableObject* instance)`. 
https://github.com/microsoft/ChakraCore/blob/7d4bdd821d452d6b91a21936257d7e352ea7dc4b/lib/Runtime/Library/JSONStringifier.cpp#L888-L899
Finally, it fails to pass the check in JSONStringifier.cpp:888, 
and go into line 897. In ReadData(), the assertion is triggered.

ISec Lab.
2020.12.16

### LINKED ISSUE #6552: warning: unsequenced modification and access to 'ib'
This warning is thrown when building master on macOS. From lib/Common/Common/NumberUtilities_strtod.cpp line 1602

This should be fixed probably by adding brackets to that line in the correct place.

### PR DESCRIPTION
**Pull request by rhuanjl**
This PR removes the Microsoft specific .getVarDate() method that is of no use without VBA interaction.

Related to that the type JavascriptVariantDate has been removed and at the same Windows RunTime Date support has been removed along with all references to them.

Drive by cleanup has also been done in a few places:
- various unnecessary fields were removed from JnDirectFields.h
- EdgeJavascriptTypeId.h was combined with TypeId.h
- removed defunct SupportsES3 and SupportsES3Extensions switches
- fixed the macOS compile time warning in lib/Common/Common/NumberUtilities_strtod.cpp
- removed the defunct exclude_chk and exclude_fre flags from runtests.py

Note the large size of the diff is due to the bytecode regen - required because of editing JnDirectFields.h and the update to the baseline for test case biops.js which used getVarDate.

Fix: #6534 
Fix: #6552

### CODE REVIEW

File: lib/Common/Common/DateUtilities.cpp [hunk 1]
```diff
@@ -68,7 +68,7 @@ namespace Js
         _u("PDT")
     };
 
-
+#ifdef INTL_WINGLOB
     //
```
Comment (rhuanjl) [inline lib/Common/Common/DateUtilities.cpp:72]: I noticed `DateUtilities::ES5DateToWinRTDate ` whilst looking for references to WinRTDate - this doesn't actually use the WinRTDate type however it is only used within `EntryIntl_FormatDateTime` and within that function it is guarded by an `#ifdef INTL_WINGLOB` - hence wrapping it with the same ifdef.

Side note the flag INTL_WINGLOB is to specify using the Windows built in Globalisation library instead of ICU - there is a lot code behind it in places that I would prefer to remove in the long term and just assume ICU will be used in all builds.

File: lib/Common/Common/NumberUtilities_strtod.cpp [hunk 2]
```diff
@@ -1599,7 +1599,8 @@ static BOOL FDblToRgbPrecise(double dbl, __out_ecount(kcbMaxRgb) byte *prgb, int
                 // Do not always push to higherBound
                 // See Js::NumberUtilities::FDblToStr for the exception
                 // i.e. we shouldn't push digits beyond interest to higherBound
-                prgb[ib++] = bT + (byte)(nDigits == -1 || ib < nDigits ? 1 : 0);
+                prgb[ib] = bT + (byte)(nDigits == -1 || ib < nDigits ? 1 : 0);
+                ++ib;
```
Comment (rhuanjl) [inline lib/Common/Common/NumberUtilities_strtod.cpp:1603]: This is unrelated to the other changes but the compile time warning this fixes was really annoying me.

File: lib/Runtime/Base/JnDirectFields.h [hunk 3]
```diff
@@ -11,7 +11,7 @@
 
 //
 // NOTE: After modifying this file you might observe unit test failures, especially jd/Debugger unit test failures.
-// This can be caused by the build-generated bytecode files for the Intl.js and Promise.js becoming invalidated.
+// This can be caused by the build-generated bytecode files for the Intl.js and JsBuiltin.js becoming invalidated.
```
Comment (rhuanjl) [inline lib/Runtime/Base/JnDirectFields.h:14]: Comment was years out of date.

File: lib/Runtime/Base/JnDirectFields.h [hunk 4]
```diff
@@ -80,6 +80,7 @@ ENTRY(clz32)
 ENTRY(fround)
 // End math functions
 
+ENTRY(Promise)
```
Comment (rhuanjl) [inline lib/Runtime/Base/JnDirectFields.h:83]: I was just removing Entry(getVarDate) but did a quick review and noticed many other Entrys here that were no longer required hence deleted a lot and re-ordered some to make it neater.

Note: this file is used to populate internal PropertyIds and BuiltInPropertyRecords.

File: lib/Runtime/Base/ScriptContext.h [hunk 5]
```diff
@@ -309,16 +309,6 @@ namespace Js
         {
         }
 
-        // Version
-        bool SupportsES3()                      const { return true; }
-        bool SupportsES3Extensions()            const {
```
Comment (rhuanjl) [inline lib/Runtime/Base/ScriptContext.h:314]: These were used to check whether to enable getVarDate.

File: lib/Runtime/Library/EngineInterfaceObject.h [hunk 6]
```diff
@@ -100,10 +100,6 @@ namespace Js
 
         static Var Entry_CallInstanceFunction(RecyclableObject *function, CallInfo callInfo, ...);
 
-#ifdef ENABLE_PROJECTION
-        static Var EntryPromise_EnqueueTask(RecyclableObject *function, CallInfo callInfo, ...);
```
Comment (rhuanjl) [inline lib/Runtime/Library/EngineInterfaceObject.h:104]: Stumbled upon this from the JnDirectFields.h review - this function doesn't exist in chakracore - so deleted.

File: lib/Runtime/Types/TypeId.h [hunk 7]
```diff
@@ -2,10 +2,140 @@
...
+      TypeIds_WebAssemblyTable = 79,
+
+      TypeIds_LastBuiltinDynamicObject = TypeIds_WebAssemblyTable,
+      TypeIds_GlobalObject = 80,
+      TypeIds_ModuleRoot = 81,
+      TypeIds_LastTrueJavascriptObjectType = TypeIds_ModuleRoot,
 
-#include "EdgeJavascriptTypeId.h"
-    // All WinRT dates are regular Javascript dates too
-    inline bool IsDateTypeId(TypeId typeId) { return (typeId == TypeIds_Date || typeId == TypeIds_WinRTDate); }
```
Comment (rhuanjl) [inline lib/Runtime/Types/TypeId.h:10]: Previously this file simply included "EdgeJavascriptTypeId.h" and defined IsDateTypeId which is now defunct - hence combined the files.

File: test/Lib/construct.js [hunk 8]
```diff
@@ -225,16 +225,12 @@ var dateList = [
 
     ["toUTCString",0],
 
-    // not in ECMA spec
```
Comment (rhuanjl) [inline test/Lib/construct.js:228]: Ironically the methods marked "not in ECMA spec" are in the ECMA spec - removed incorrect comment, same in several places below.

File: test/Operators/biops.js [hunk 9]
```diff
@@ -46,10 +46,19 @@ var biops = [
...
 
+function fixDate(output)
+{
+    if (output instanceof Date)
+    {
+        return output.toUTCString();
+    }
+    return output;
+}
+
```
Comment (rhuanjl) [inline test/Operators/biops.js:57]: This test which used getVarDate was also marked as exclude_jenkins due to outputting dates to compare against a baseline - which was timezone dependent - I've tried to fix that here.

File: lib/Runtime/Library/JavascriptLibrary.cpp [hunk 10]
```diff
@@ -2979,7 +2978,7 @@ namespace Js
 
     bool JavascriptLibrary::InitializeDatePrototype(DynamicObject* datePrototype, DeferredTypeHandlerBase * typeHandler, DeferredInitializeMode mode)
     {
-        typeHandler->Convert(datePrototype, mode, 51);
+        typeHandler->Convert(datePrototype, mode, 48);
```
Comment (rhuanjl) [inline lib/Runtime/Library/JavascriptLibrary.cpp:2981]: Expected to decrease this by 1 (to avoid allocating space for a pointer to getVarDate) but counted all of the members of the datePrototype and found only 48 not 50 so dropped to 48.

I'm going to make a follow up PR to review all of the Initialisation methods and check that they're allocating the right number of slots + add assertions to avoid future mistakes. EDIT: for now it's a follow up issue as not quite as straight forward as I hoped - see #6563

**Review by Fly-Style — APPROVED** [review]
