### PR TITLE
Make Linux build python version agnostic

### LINKED ISSUE #6731: Build.sh may be broken on latest Ubuntu
Whilst it is now possible to build directly with cmake and skip the build.sh script altogether whilst we continue to provide it we should keep it functional...

New versions of Ubuntu ship without Python2.

Build.sh reference to Python2 for optional LLTng support; AND for setting a relative path and this can cause a build failure on Ubuntu 20 - as per @fatcerberus

We should update build.sh to try checking for python 3 if python 2 is not found.

### PR DESCRIPTION
**Pull request by rhuanjl**
Ubuntu 20.04 comes with python3 only AND its shell python command is `python3` not `python`.

Older linux distros come with python 2 only.

**Two changes to handle this**
1. Our `build.sh` script was dependent on finding python2, this change should cause it to function with python3 or python2
2. the `jstoc.py` script run as part of building `ch` required a command line `python` command, this change asks CMake to locate a python executable and use it rather than relying on the existence of a command line `python` command

**Note this was not an issue in CI because:**
a) we don't use `build.sh` in the CI AND
b) the CI machines have a symlink between `python` and `python3` - but this is something in azure CI, it's not default on a blank Ubuntu 20.04 distro

**CC** @fatcerberus 

Fix #6731

### CODE REVIEW

**Review by ppenzin — APPROVED** [review]
Looks good, this is a much cleaner way to handle it.

File: build.sh [hunk 1]
```diff
@@ -127,7 +128,7 @@ CMAKE_EXPORT_COMPILE_COMMANDS="-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
 LIBS_ONLY_BUILD=
 ALWAYS_YES=
 CCACHE_NAME=
-PYTHON2_BINARY=$(which python2.7 || which python2 || which python 2> /dev/null)
+PYTHON_BINARY=$(which python3 || which python || which python2.7 || which python2 || which python 2> /dev/null)
```
Comment (fatcerberus) [inline build.sh:131]: `which python` is called twice - is that intentional? It seems if the first one fails, the second will also.
